/**
 * Checked-in browser-safe chapter checkpoints generated by
 * chapter-pacing-audit.mjs. These are diagnostics, never playtime proof.
 */

const deepFreeze = (value) => {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.values(value).forEach(deepFreeze);
  return Object.freeze(value);
};

export const CHAPTER_PACING_CHECKPOINTS = deepFreeze({
  schemaVersion: 1,
  campaignId: 'bells-black-chrysanthemum',
  scenario: 'reference',
  scope: 'complete-215-activity-intended-route-at-1x',
  diagnosticOnly: true,
  observedPlaytimeProof: false,
  aggregateTargetMs: 73_901_133,
  aggregateTargetMinutes: 1_231.686,
  allocation: 'component-attributed shipped quantities; whole milliseconds reconciled by largest remainder',
  chapters: [
    { chapterId: 'prologue', number: 0, title: 'The Night Census', targetMs: 3_274_233, targetMinutes: 54.571, share: 0.044306 },
    { chapterId: 'chapter-1', number: 1, title: 'River of Names', targetMs: 3_564_933, targetMinutes: 59.416, share: 0.048239 },
    { chapterId: 'chapter-2', number: 2, title: 'Bell at Takamine', targetMs: 5_328_784, targetMinutes: 88.813, share: 0.072107 },
    { chapterId: 'chapter-3', number: 3, title: 'Sodegaura Lanterns', targetMs: 7_328_193, targetMinutes: 122.137, share: 0.099162 },
    { chapterId: 'chapter-4', number: 4, title: 'The Sea Keeps No Ledger', targetMs: 8_475_817, targetMinutes: 141.264, share: 0.114691 },
    { chapterId: 'chapter-5', number: 5, title: 'Ash in Kagura Pass', targetMs: 8_983_030, targetMinutes: 149.717, share: 0.121555 },
    { chapterId: 'chapter-6', number: 6, title: 'The Court of Masks', targetMs: 5_712_950, targetMinutes: 95.216, share: 0.077305 },
    { chapterId: 'chapter-7', number: 7, title: 'The Road of the Dead', targetMs: 6_504_610, targetMinutes: 108.41, share: 0.088018 },
    { chapterId: 'chapter-8', number: 8, title: 'Lanterns Unhidden', targetMs: 5_555_550, targetMinutes: 92.593, share: 0.075175 },
    { chapterId: 'chapter-9', number: 9, title: 'The Black Chrysanthemum', targetMs: 11_167_550, targetMinutes: 186.126, share: 0.151115 },
    { chapterId: 'epilogue', number: 10, title: 'Names at Daybreak', targetMs: 8_005_483, targetMinutes: 133.425, share: 0.108327 },
  ],
  signature: 'fnv1a32:8107b2cd',
});

export function getChapterPacingCheckpoint(chapterId) {
  return CHAPTER_PACING_CHECKPOINTS.chapters.find((chapter) => chapter.chapterId === chapterId) ?? null;
}
