/**
 * Checked-in browser-safe chapter checkpoints generated by
 * chapter-pacing-audit.mjs. These are diagnostics, never playtime proof.
 */

const deepFreeze = (value) => {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.values(value).forEach(deepFreeze);
  return Object.freeze(value);
};

export const CHAPTER_PACING_CHECKPOINTS = deepFreeze({
  schemaVersion: 1,
  campaignId: 'bells-black-chrysanthemum',
  scenario: 'reference',
  scope: 'complete-215-activity-intended-route-at-1x',
  diagnosticOnly: true,
  observedPlaytimeProof: false,
  aggregateTargetMs: 74_602_000,
  aggregateTargetMinutes: 1_243.367,
  allocation: 'component-attributed shipped quantities; whole milliseconds reconciled by largest remainder',
  chapters: [
    { chapterId: 'prologue', number: 0, title: 'The Night Census', targetMs: 3_274_233, targetMinutes: 54.571, share: 0.043889 },
    { chapterId: 'chapter-1', number: 1, title: 'River of Names', targetMs: 3_565_267, targetMinutes: 59.421, share: 0.047791 },
    { chapterId: 'chapter-2', number: 2, title: 'Bell at Takamine', targetMs: 5_372_950, targetMinutes: 89.549, share: 0.072022 },
    { chapterId: 'chapter-3', number: 3, title: 'Sodegaura Lanterns', targetMs: 7_394_010, targetMinutes: 123.234, share: 0.099113 },
    { chapterId: 'chapter-4', number: 4, title: 'The Sea Keeps No Ledger', targetMs: 8_494_817, targetMinutes: 141.58, share: 0.113868 },
    { chapterId: 'chapter-5', number: 5, title: 'Ash in Kagura Pass', targetMs: 8_983_030, targetMinutes: 149.717, share: 0.120413 },
    { chapterId: 'chapter-6', number: 6, title: 'The Court of Masks', targetMs: 5_769_350, targetMinutes: 96.156, share: 0.077335 },
    { chapterId: 'chapter-7', number: 7, title: 'The Road of the Dead', targetMs: 6_610_993, targetMinutes: 110.183, share: 0.088617 },
    { chapterId: 'chapter-8', number: 8, title: 'Lanterns Unhidden', targetMs: 5_588_817, targetMinutes: 93.147, share: 0.074915 },
    { chapterId: 'chapter-9', number: 9, title: 'The Black Chrysanthemum', targetMs: 11_543_050, targetMinutes: 192.384, share: 0.154728 },
    { chapterId: 'epilogue', number: 10, title: 'Names at Daybreak', targetMs: 8_005_483, targetMinutes: 133.425, share: 0.107309 },
  ],
  signature: 'fnv1a32:7b3c538b',
});

export function getChapterPacingCheckpoint(chapterId) {
  return CHAPTER_PACING_CHECKPOINTS.chapters.find((chapter) => chapter.chapterId === chapterId) ?? null;
}
