/**
 * Authored level-kit data for Bells of the Black Chrysanthemum.
 *
 * Coordinates use a top-left origin. Tile keys are `x,y`, zero-based, and
 * integer-only. Field kits are 20 x 12; combat stages are 12 x 7. A runtime
 * owns pathfinding, animation, and collision resolution; this module only
 * supplies serializable level facts and small lookup helpers.
 */

export const LEVEL_SCHEMA_VERSION = 1;

export const TERRAIN_TAGS = {
  'wet-stone': {
    label: 'Wet stone',
    passable: true,
    visual: 'rain-blue hard highlight',
  },
  'shallow-puddle': {
    label: 'Shallow puddle',
    passable: true,
    visual: 'two-value rain reflection; no damage',
  },
  'paper-litter': {
    label: 'Paper litter',
    passable: true,
    visual: 'pale scraps that identify a registry route',
  },
  'cracked-board': {
    label: 'Cracked board',
    passable: true,
    visual: 'split cedar with a pale exposed edge',
  },
  'swing-beam-lane': {
    label: 'Swinging bell beam lane',
    passable: true,
    visual: 'moving shadow and a 0.5-second creak cue',
  },
  water: {
    label: 'Water',
    passable: true,
    visual: 'blue-black tile with one-pixel ripple',
  },
  'dry-lantern': {
    label: 'Dry lantern space',
    passable: true,
    visual: 'warm stepped light; safe terrain',
  },
  'high-gallery': {
    label: 'Raised gallery',
    passable: false,
    visual: 'black-lacquer railing and gold edge',
  },
  'storm-water': {
    label: 'Storm water',
    passable: true,
    visual: 'yellow-white charge over rain water',
  },
  'cold-pool': {
    label: 'Cold pool',
    passable: true,
    visual: 'pale cyan reflection',
  },
  'ash-field': {
    label: 'Ash field',
    passable: true,
    visual: 'grey cinders with ember pinpricks',
  },
  'furnace-grate': {
    label: 'Furnace grate',
    passable: true,
    visual: 'orange underlight through iron slots',
  },
  'legal-seal': {
    label: 'Legal seal zone',
    passable: true,
    visual: 'vermilion seal with black calligraphic ring',
  },
  'flowing-water': {
    label: 'Flowing water',
    passable: true,
    visual: 'bright moving current used to return name slips',
  },
  'ember-ash': {
    label: 'Ember ash',
    passable: true,
    visual: 'orange ash clumps',
  },
  'umbral-ash': {
    label: 'Umbral ash',
    passable: true,
    visual: 'violet-black ash clumps',
  },
  'bell-node': {
    label: 'Bell node',
    passable: true,
    visual: 'black metal root with parchment threads',
  },
  'archive-floor': {
    label: 'Archive floor',
    passable: true,
    visual: 'cedar boards and pale paper runners',
  },
};

const rainPalette = {
  id: 'takamine-rain',
  shadow: '#0b1020',
  ground: '#26334a',
  accent: '#b65c4d',
  light: '#e6cb80',
};

const archivePalette = {
  id: 'archive-indigo',
  shadow: '#0a0d1b',
  ground: '#242742',
  accent: '#987cc0',
  light: '#e8dcc0',
};

const coastPalette = {
  id: 'coast-fog',
  shadow: '#0b1422',
  ground: '#315469',
  accent: '#d1b66a',
  light: '#b9d8d4',
};

const ashPalette = {
  id: 'kagura-ash',
  shadow: '#130e18',
  ground: '#4a3b3b',
  accent: '#dd7042',
  light: '#d8c6a6',
};

const courtPalette = {
  id: 'court-vermilion',
  shadow: '#120d1c',
  ground: '#34223a',
  accent: '#b84748',
  light: '#dfc16f',
};

/**
 * `blocked` is deliberately separate from terrain: a renderer can paint a
 * water tile under an actor while simulation rejects only `blocked` tiles.
 * Dynamic blockers and hazards name their state change in `hazards`.
 */
function sceneHub(config) {
  return {
    kind: 'field',
    width: 20,
    height: 12,
    spacePx: 16,
    blocked: [],
    terrain: [],
    hazards: [],
    spawn: { x: 2, y: 9, facing: 'north', formation: ['ren'] },
    exits: [],
    objective: 'Explore the authored scene.',
    palette: archivePalette,
    interactables: [],
    lesson: 'A readable hub gives the player a concrete local objective before the next route.',
    ...config,
  };
}

export const LEVELS = [
  {
    id: 'hsh-census-square',
    chapterId: 'prologue',
    primary: true,
    name: 'Hoshigawa Census Square',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['4,0', '5,0', '6,0', '7,0', '4,1', '7,1', '5,2', '6,2', '0,3', '11,3', '0,4', '11,4'],
    terrain: [
      { at: '1,5', tag: 'wet-stone' },
      { at: '2,5', tag: 'wet-stone' },
      { at: '8,4', tag: 'wet-stone' },
      { at: '10,5', tag: 'shallow-puddle' },
    ],
    hazards: [
      {
        id: 'census-bell-sweep',
        trigger: 'enemyTelegraph',
        tiles: ['3,4', '4,4', '5,4', '6,4', '7,4'],
        effect: { type: 'physicalDamage', delivery: 'crush', push: { spaces: 1, direction: 'south' } },
        cue: 'A red line grows across the square one activation before impact.',
      },
    ],
    spawn: { x: 1, y: 5, facing: 'east', formation: ['ren'] },
    exits: [
      { id: 'river-exit', at: '11,5', destinationLevelId: 'hsh-riverbank', condition: 'survived-three-activations' },
    ],
    objective: 'Survive three Ashen Bailiff activations and reach the marked river exit.',
    palette: rainPalette,
    interactables: [{ id: 'fractured-bell', at: '6,1', action: 'story', state: 'blocked-until-objective' }],
    lesson: 'Pace is spent before a command; telegraphs invite a measured move, not a reflex dodge.',
  },

  {
    id: 'c1-tax-storehouse',
    chapterId: 'chapter-1',
    primary: true,
    name: 'Abandoned Tax Storehouse',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '2,0', '9,0', '10,0', '11,0', '2,2', '3,2', '8,2', '9,2', '0,6', '1,6', '10,6', '11,6'],
    terrain: [
      { at: '4,1', tag: 'paper-litter' },
      { at: '5,1', tag: 'paper-litter' },
      { at: '6,1', tag: 'paper-litter' },
      { at: '5,4', tag: 'paper-litter' },
      { at: '6,4', tag: 'paper-litter' },
    ],
    hazards: [
      {
        id: 'consumed-ink-line',
        trigger: 'enemyTelegraph',
        tiles: ['3,3', '4,3', '5,3', '6,3', '7,3'],
        effect: { type: 'status', status: 'dread', duration: 'until-exposed-seal-hit' },
        cue: 'Black letters lift from the ledger and point along a five-space line.',
      },
    ],
    spawn: { x: 5, y: 5, facing: 'north', formation: ['ren', 'aya'] },
    exits: [{ id: 'clerk-room', at: '10,4', destinationLevelId: 'c1-ferry-landing', condition: 'boss-resolved' }],
    objective: 'Expose the Tithe Hound seal, preserve copied names, and defeat the ledger predator.',
    palette: archivePalette,
    interactables: [
      { id: 'copy-table', at: '1,4', action: 'copy-evidence', state: 'available-after-boss' },
      { id: 'ledger-brazier', at: '10,2', action: 'destroy-weaponized-ledger', state: 'available-after-copy' },
    ],
    lesson: 'Analyze reveals a delivery weakness; a boss telegraph creates room for a longer Recovery commitment.',
  },

  {
    id: 'tkm-rain-gate',
    chapterId: 'chapter-2',
    name: 'FP-00 Rain Gate',
    kind: 'field',
    width: 20,
    height: 12,
    spacePx: 16,
    blocked: [
      '0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '6,0', '7,0', '8,0', '9,0', '10,0', '11,0', '12,0', '13,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0',
      '6,1', '7,1', '8,1', '9,1', '10,1', '11,1', '12,1', '13,1',
      '5,2', '6,2', '7,2', '8,2', '9,2', '10,2', '11,2', '12,2', '13,2', '14,2',
      '5,3', '6,3', '7,3', '8,3', '9,3', '10,3', '11,3', '12,3', '13,3', '14,3',
      '1,4', '2,4', '3,4', '15,4', '16,4', '17,4', '1,5', '17,5', '1,6', '17,6',
    ],
    terrain: [
      { at: '2,9', tag: 'wet-stone' },
      { at: '3,9', tag: 'wet-stone' },
      { at: '4,9', tag: 'wet-stone' },
      { at: '15,7', tag: 'shallow-puddle' },
      { at: '16,7', tag: 'shallow-puddle' },
    ],
    hazards: [],
    spawn: { x: 2, y: 9, facing: 'north', formation: ['ren', 'aya'] },
    exits: [{ id: 'service-path', at: '18,3', destinationLevelId: 'tkm-cedar-service-path', condition: 'inspect-supply-cart' }],
    objective: 'Inspect the supply cart, then reach the service-path threshold beside the locked front gate.',
    palette: rainPalette,
    interactables: [
      { id: 'locked-main-gate', at: '10,3', action: 'inspect', text: 'The front gate is barred from within.' },
      { id: 'supply-cart', at: '5,8', action: 'inspect', text: 'Blank forms. Fresh ink. No food.' },
    ],
    lesson: 'Eight-direction field movement, clear interaction range, and an obvious non-gated alternate route.',
  },

  {
    id: 'tkm-cedar-service-path',
    chapterId: 'chapter-2',
    name: 'FP-01 Cedar Service Path',
    kind: 'field',
    width: 20,
    height: 12,
    spacePx: 16,
    blocked: [
      '0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '6,0', '7,0', '8,0', '9,0', '10,0', '11,0', '12,0', '13,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0',
      '0,1', '1,1', '2,1', '3,1', '4,1', '5,1', '13,1', '14,1', '15,1', '16,1', '17,1', '18,1', '19,1',
      '0,7', '1,7', '2,7', '3,7', '11,7', '12,7', '13,7', '14,7', '15,7', '16,7', '17,7',
      '8,8', '9,8', '10,8', '8,9', '10,9', '8,10', '9,10', '10,10',
    ],
    terrain: [
      { at: '4,5', tag: 'shallow-puddle' },
      { at: '5,5', tag: 'shallow-puddle' },
      { at: '13,5', tag: 'shallow-puddle' },
      { at: '14,5', tag: 'shallow-puddle' },
      { at: '5,9', tag: 'paper-litter' },
    ],
    hazards: [],
    spawn: { x: 1, y: 9, facing: 'north-east', formation: ['ren', 'aya'] },
    exits: [{ id: 'chapel-service-door', at: '18,3', destinationLevelId: 'tkm-abandoned-chapel', condition: 'fp1-cedar-path-cleared' }],
    objective: 'Clear the path encounter, inspect the optional side chest, and reach the chapel service door.',
    palette: rainPalette,
    interactables: [
      { id: 'temple-charm-chest', at: '6,9', action: 'loot', optional: true, reward: 'Defaced Registry Token' },
      { id: 'loading-alcove-sheet', at: '16,4', action: 'inspect', text: 'A torn confession sheet waits for an empty signature.' },
    ],
    encounterTriggers: [{ id: 'cedar-path-ambush', encounterId: 'fp1-cedar-path', tiles: ['11,4', '12,4', '11,5', '12,5'], once: true }],
    lesson: 'Combat is authored, not random; side rewards require careful walking rather than a traversal power.',
  },

  {
    id: 'fp1-wet-cedar-stage',
    chapterId: 'chapter-2',
    name: 'Wet Cedar Path Battle Stage',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '2,0', '9,0', '10,0', '11,0', '0,1', '11,1', '0,5', '11,5', '0,6', '1,6', '10,6', '11,6', '4,2', '7,2'],
    terrain: [
      { at: '4,3', tag: 'shallow-puddle' },
      { at: '7,3', tag: 'shallow-puddle' },
      { at: '5,4', tag: 'wet-stone' },
      { at: '6,4', tag: 'wet-stone' },
    ],
    hazards: [],
    spawn: { x: 5, y: 5, facing: 'north', formation: ['ren', 'aya'] },
    exits: [{ id: 'continue-path', at: '6,0', destinationLevelId: 'tkm-cedar-service-path', condition: 'defeat-all' }],
    objective: 'Defeat two Cinder Hounds and one Ash Wisp while reading Cut resistance and a three-space lunge.',
    palette: rainPalette,
    interactables: [],
    lesson: 'Spend two Pace, use Analyze after a readable resisted strike, then leave a telegraphed lane or Guard.',
  },

  {
    id: 'tkm-abandoned-chapel',
    chapterId: 'chapter-2',
    name: 'FP-02 Abandoned Chapel',
    kind: 'field',
    width: 20,
    height: 12,
    spacePx: 16,
    blocked: [
      '0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '6,0', '7,0', '8,0', '9,0', '10,0', '11,0', '12,0', '13,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0',
      '1,1', '2,1', '3,1', '4,1', '5,1', '6,1', '14,1', '15,1', '16,1', '17,1', '18,1',
      '1,2', '6,2', '14,2', '18,2', '1,3', '6,3', '14,3', '18,3',
      '2,7', '3,7', '4,7', '11,7', '12,7', '13,7', '2,8', '13,8',
      '8,3', '9,3', '10,3', '8,4', '9,4', '10,4',
    ],
    terrain: [
      { at: '7,2', tag: 'paper-litter' },
      { at: '12,3', tag: 'paper-litter' },
      { at: '15,7', tag: 'wet-stone' },
    ],
    hazards: [],
    spawn: { x: 2, y: 9, facing: 'north', formation: ['ren', 'aya'] },
    exits: [{ id: 'rear-door', at: '18,5', destinationLevelId: 'tkm-bell-stair', condition: 'lise-key-used' }],
    objective: 'Speak to witnesses, meet Lise, and open the rear door with her stolen key.',
    palette: archivePalette,
    interactables: [
      { id: 'prisoner-grate-west', at: '4,5', action: 'talk', optional: true, result: 'casebook-note-west' },
      { id: 'prisoner-grate-east', at: '15,5', action: 'talk', optional: true, result: 'casebook-note-east' },
      { id: 'hidden-key-screen', at: '12,2', action: 'inspect', optional: true, result: 'reveal-lise-entry-route' },
      { id: 'rear-lock', at: '17,5', action: 'unlock', requires: 'c2_lise_trusted_with_key' },
    ],
    lesson: 'Witness interactions are meaningful but optional; a new party member changes tactics without a forced fight.',
  },

  {
    id: 'tkm-bell-stair',
    chapterId: 'chapter-2',
    name: 'FP-03 Bell Stair',
    kind: 'field',
    width: 20,
    height: 12,
    spacePx: 16,
    blocked: [
      '0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '6,0', '7,0', '8,0', '9,0', '10,0', '11,0', '12,0', '13,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0',
      '0,1', '1,1', '2,1', '3,1', '4,1', '5,1', '14,1', '15,1', '16,1', '17,1', '18,1', '19,1',
      '0,2', '1,2', '2,2', '3,2', '4,2', '5,2', '14,2', '15,2', '16,2', '17,2', '18,2', '19,2',
      '0,8', '1,8', '2,8', '3,8', '4,8', '5,8', '14,8', '15,8', '16,8', '17,8', '18,8', '19,8',
      '0,9', '1,9', '2,9', '3,9', '4,9', '5,9', '14,9', '15,9', '16,9', '17,9', '18,9', '19,9',
      '2,4', '3,4', '4,4', '15,4', '16,4', '17,4', '2,6', '3,6', '4,6', '15,6', '16,6', '17,6',
    ],
    terrain: [
      { at: '7,3', tag: 'swing-beam-lane' },
      { at: '8,3', tag: 'swing-beam-lane' },
      { at: '9,3', tag: 'swing-beam-lane' },
      { at: '10,3', tag: 'swing-beam-lane' },
      { at: '11,3', tag: 'swing-beam-lane' },
      { at: '7,7', tag: 'cracked-board' },
      { at: '8,7', tag: 'cracked-board' },
      { at: '12,7', tag: 'cracked-board' },
    ],
    hazards: [
      {
        id: 'loose-bell-beam',
        trigger: 'cycle',
        periodMs: 2500,
        warningMs: 500,
        tiles: ['7,3', '8,3', '9,3', '10,3', '11,3'],
        effect: { type: 'fieldDamage', percentMaxHp: 15, returnTo: 'prior-safe-landing', minimumHp: 1 },
        cue: 'A shadow crosses the lane, followed by a creak before the beam swings.',
      },
      {
        id: 'cracked-boards',
        trigger: 'onEnterDelay',
        delayMs: 750,
        tiles: ['7,7', '8,7', '12,7'],
        resetMs: 1000,
        effect: { type: 'returnTo', target: 'prior-safe-landing', minimumHp: 1 },
        cue: 'Boards split wider, then drop; the route resets rather than killing the party.',
      },
    ],
    spawn: { x: 6, y: 10, facing: 'north', formation: ['ren', 'aya', 'lise'] },
    exits: [{ id: 'undercroft-hatch', at: '13,2', destinationLevelId: 'tkm-flooded-undercroft', condition: 'inspect-varga-mark' }],
    objective: 'Cross the beam and cracked boards, light the checkpoint lantern, then inspect the Varga mark.',
    palette: rainPalette,
    interactables: [
      { id: 'checkpoint-lantern', at: '11,6', action: 'checkpoint', saves: true, restores: false },
      { id: 'varga-mark', at: '13,3', action: 'inspect', result: 'varga-mark-recorded' },
    ],
    lesson: 'Precise field movement is observable and forgiving: no jump, no instant kill, no hidden collision.',
  },

  {
    id: 'tkm-flooded-undercroft',
    chapterId: 'chapter-2',
    name: 'FP-04 Flooded Undercroft',
    kind: 'field',
    width: 20,
    height: 12,
    spacePx: 16,
    blocked: [
      '0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '6,0', '7,0', '8,0', '9,0', '10,0', '11,0', '12,0', '13,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0',
      '1,1', '2,1', '3,1', '4,1', '5,1', '6,1', '13,1', '14,1', '15,1', '16,1', '17,1', '18,1',
      '1,2', '6,2', '13,2', '18,2', '1,3', '6,3', '13,3', '18,3',
      '2,5', '3,5', '4,5', '5,5', '14,5', '15,5', '16,5', '17,5',
      '2,9', '3,9', '4,9', '5,9', '14,9', '15,9', '16,9', '17,9',
    ],
    terrain: [
      { at: '7,4', tag: 'water' },
      { at: '8,4', tag: 'water' },
      { at: '9,4', tag: 'water' },
      { at: '10,4', tag: 'water' },
      { at: '11,4', tag: 'water' },
      { at: '12,4', tag: 'water' },
      { at: '7,5', tag: 'water' },
      { at: '8,5', tag: 'water' },
      { at: '9,5', tag: 'water' },
      { at: '10,5', tag: 'water' },
      { at: '11,5', tag: 'water' },
      { at: '12,5', tag: 'water' },
      { at: '3,7', tag: 'dry-lantern' },
      { at: '4,7', tag: 'dry-lantern' },
      { at: '12,7', tag: 'paper-litter' },
    ],
    hazards: [
      {
        id: 'storm-water-chill',
        trigger: 'onEnterConditional',
        condition: 'storm-strike-resolved-this-round',
        tiles: ['7,4', '8,4', '9,4', '10,4', '11,4', '12,4', '7,5', '8,5', '9,5', '10,5', '11,5', '12,5'],
        effect: { type: 'status', status: 'chill', paceDeltaNextActivation: -1 },
        cue: 'The inspectable brazier names the rule before the battle trigger.',
      },
    ],
    spawn: { x: 3, y: 10, facing: 'north', formation: ['ren', 'aya', 'lise'] },
    exits: [{ id: 'bell-door', at: '18,4', destinationLevelId: 'tkm-bell-chamber', condition: 'bell-room-key' }],
    objective: 'Inspect the charged water rule, defeat the archive encounter, and unlock the bell door.',
    palette: archivePalette,
    interactables: [
      { id: 'name-slip-shelf', at: '4,4', action: 'inspect', result: 'fed-bell-scene' },
      { id: 'storm-brazier', at: '3,7', action: 'inspect', text: 'Storm charge in water causes Chill; the lantern space is safe.' },
      { id: 'sealed-bell-door', at: '18,4', action: 'unlock', requires: 'bell-room-key' },
    ],
    encounterTriggers: [{ id: 'flooded-archive-guard', encounterId: 'fp1-flooded-archive', tiles: ['12,4', '13,4', '12,5', '13,5'], once: true }],
    lesson: 'Inspect terrain before fighting; an ally can set an angle while another protects a water lane.',
  },

  {
    id: 'fp1-flooded-archive-stage',
    chapterId: 'chapter-2',
    name: 'Flooded Archive Battle Stage',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '2,0', '9,0', '10,0', '11,0', '1,1', '2,1', '3,1', '8,1', '9,1', '10,1', '0,4', '11,4', '0,5', '11,5'],
    terrain: [
      { at: '4,2', tag: 'water' },
      { at: '5,2', tag: 'water' },
      { at: '6,2', tag: 'water' },
      { at: '7,2', tag: 'water' },
      { at: '4,3', tag: 'water' },
      { at: '7,3', tag: 'water' },
      { at: '1,4', tag: 'dry-lantern' },
      { at: '10,4', tag: 'dry-lantern' },
    ],
    hazards: [
      {
        id: 'archive-storm-water',
        trigger: 'onEnterConditional',
        condition: 'storm-strike-resolved-this-round',
        tiles: ['4,2', '5,2', '6,2', '7,2', '4,3', '7,3'],
        effect: { type: 'status', status: 'chill', paceDeltaNextActivation: -1 },
        cue: 'A charged ripple traverses the water only after a Storm attack.',
      },
    ],
    spawn: { x: 5, y: 6, facing: 'north', formation: ['ren', 'aya', 'lise'] },
    exits: [{ id: 'bell-door', at: '6,0', destinationLevelId: 'tkm-bell-chamber', condition: 'defeat-all' }],
    objective: 'Defeat the Tithe Enforcer and Bell Moths without letting forced movement turn the water into a surprise.',
    palette: archivePalette,
    interactables: [],
    lesson: 'Read a terrain condition, flank a Guarded target with Pierce, and use enemy Recovery to choose a heavy attack.',
  },

  {
    id: 'tkm-bell-chamber',
    chapterId: 'chapter-2',
    primary: true,
    name: 'FP-05 Bell Chamber',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '2,0', '9,0', '10,0', '11,0', '0,6', '1,6', '2,6', '9,6', '10,6', '11,6', '5,2', '6,2', '5,3', '6,3'],
    terrain: [
      { at: '0,2', tag: 'high-gallery' },
      { at: '0,3', tag: 'high-gallery' },
      { at: '0,4', tag: 'high-gallery' },
      { at: '5,1', tag: 'bell-node' },
      { at: '6,5', tag: 'bell-node' },
      { at: '3,1', tag: 'dry-lantern' },
      { at: '3,5', tag: 'dry-lantern' },
    ],
    hazards: [
      {
        id: 'crimson-litany-line',
        trigger: 'bossTelegraph',
        dynamic: true,
        shape: { type: 'line', length: 4, origin: 'mateus-facing' },
        effect: { type: 'damage', delivery: 'arcane', essence: 'umbral', status: 'dread', duration: 'one-activation' },
        cue: 'Two rising bell-note activations draw a violet line before the hit.',
      },
      {
        id: 'sanguine-step-endpoint',
        trigger: 'bossTelegraph',
        dynamic: true,
        shape: { type: 'laneEndpoint', length: 2, origin: 'mateus-afterimage' },
        effect: { type: 'damage', delivery: 'cut', essence: 'umbral' },
        cue: 'A red afterimage marks the landing space one activation before the slash.',
      },
    ],
    spawn: { x: 2, y: 3, facing: 'east', formation: ['ren', 'aya', 'lise'] },
    exits: [{ id: 'cell-block-door', at: '11,3', destinationLevelId: 'tkm-cell-block', condition: 'mateus-yields' }],
    objective: 'Reduce Mateus to 20% health or break both Blood Ward seals after phase two; he must not be killed.',
    palette: archivePalette,
    interactables: [
      { id: 'buried-black-bell', at: '5,2', action: 'story', state: 'boss-only' },
      { id: 'blood-ward-west', at: '5,1', action: 'targetable-summon', state: 'spawned-by-blood-ward' },
      { id: 'blood-ward-east', at: '6,5', action: 'targetable-summon', state: 'spawned-by-blood-ward' },
    ],
    lesson: 'Telegraphs are not dead time: avoid a line, then spend a visible three-Recovery window on damage or recovery.',
  },

  {
    id: 'tkm-cell-block',
    chapterId: 'chapter-2',
    name: 'FP-06 Cell Block Exit',
    kind: 'field',
    width: 20,
    height: 12,
    spacePx: 16,
    blocked: [
      '0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '6,0', '7,0', '8,0', '9,0', '10,0', '11,0', '12,0', '13,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0',
      '1,2', '2,2', '3,2', '5,2', '6,2', '7,2', '9,2', '10,2', '11,2', '1,7', '2,7', '3,7', '5,7', '6,7', '7,7', '9,7', '10,7', '11,7',
      '1,3', '3,3', '5,3', '7,3', '9,3', '11,3', '1,6', '3,6', '5,6', '7,6', '9,6', '11,6',
    ],
    terrain: [{ at: '15,8', tag: 'wet-stone' }, { at: '16,8', tag: 'wet-stone' }],
    hazards: [],
    spawn: { x: 2, y: 10, facing: 'north', formation: ['ren', 'aya', 'lise'] },
    exits: [{ id: 'rain-lit-exit', at: '18,9', destinationLevelId: 'sdg-market-lane', condition: 'cell-lever-pulled' }],
    objective: 'Pull the cell lever, free witnesses, and leave through the rain-lit service exit.',
    palette: archivePalette,
    interactables: [
      { id: 'cell-lever', at: '13,5', action: 'pull', result: 'open-six-cells' },
      { id: 'rain-exit-door', at: '18,9', action: 'exit', requires: 'open-six-cells' },
    ],
    lesson: 'After a boss, the player performs the consequential rescue rather than only watching it.',
  },

  {
    id: 'sdg-salt-warehouse',
    chapterId: 'chapter-3',
    primary: true,
    name: 'Sodegaura Salt Warehouse Platform',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '2,2', '3,2', '8,2', '9,2', '0,6', '1,6', '10,6', '11,6'],
    terrain: [
      { at: '4,1', tag: 'storm-water' },
      { at: '5,1', tag: 'storm-water' },
      { at: '6,1', tag: 'storm-water' },
      { at: '7,1', tag: 'storm-water' },
      { at: '4,5', tag: 'storm-water' },
      { at: '5,5', tag: 'storm-water' },
      { at: '6,5', tag: 'storm-water' },
      { at: '7,5', tag: 'storm-water' },
    ],
    hazards: [
      {
        id: 'charged-dock-water',
        trigger: 'endActivation',
        tiles: ['4,1', '5,1', '6,1', '7,1', '4,5', '5,5', '6,5', '7,5'],
        effect: { type: 'damage', delivery: 'arcane', essence: 'storm', status: 'shock', duration: 'one-activation' },
        cue: 'Dock cranes arc once before water becomes dangerous.',
      },
    ],
    spawn: { x: 2, y: 4, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'genta'] },
    exits: [{ id: 'key-crane', at: '10,3', destinationLevelId: 'sdg-rain-docks', condition: 'kaji-disarmed-and-witnesses-safe' }],
    objective: 'Disarm Captain Kaji while keeping the witness spaces clear of hook drags and storm water.',
    palette: coastPalette,
    interactables: [{ id: 'first-bell-key-crane', at: '10,3', action: 'claim', state: 'available-after-boss' }],
    lesson: 'Facing and Guard make forced movement legible; Genta anchors an ally before a hook resolves.',
  },

  {
    id: 'ngi-storm-reef',
    chapterId: 'chapter-4',
    primary: true,
    name: 'Nagi Storm-Broken Reef',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '3,1', '8,1', '1,3', '10,3', '3,5', '8,5', '0,6', '1,6', '10,6', '11,6'],
    terrain: [
      { at: '4,1', tag: 'cold-pool' },
      { at: '5,1', tag: 'cold-pool' },
      { at: '6,1', tag: 'cold-pool' },
      { at: '7,1', tag: 'cold-pool' },
      { at: '4,5', tag: 'cold-pool' },
      { at: '5,5', tag: 'cold-pool' },
      { at: '6,5', tag: 'cold-pool' },
      { at: '7,5', tag: 'cold-pool' },
      { at: '2,3', tag: 'dry-lantern' },
      { at: '9,3', tag: 'dry-lantern' },
    ],
    hazards: [
      {
        id: 'tide-switch',
        trigger: 'bossPhaseCycle',
        states: ['high-tide', 'low-tide'],
        everyBossActivations: 2,
        effect: { type: 'terrainStateSwap', highTideSafe: ['2,3', '9,3'], lowTideSafe: ['4,1', '5,1', '6,1', '7,1', '4,5', '5,5', '6,5', '7,5'] },
        cue: 'The waterline retracts or climbs one full activation before tiles change state.',
      },
    ],
    spawn: { x: 2, y: 4, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'genta', 'kiku'] },
    exits: [{ id: 'wreck-hold', at: '10,2', destinationLevelId: 'ngi-wrecked-carrack', condition: 'widow-names-returned' }],
    objective: 'Use dry lantern spaces and tide cues to release the Widow-of-Fog and recover the second key.',
    palette: coastPalette,
    interactables: [{ id: 'second-bell-key', at: '6,3', action: 'claim', state: 'available-after-boss' }],
    lesson: 'Elemental terrain changes on a declared cadence; Ember creates safety while Frost is a poor answer to the boss.',
  },

  {
    id: 'kgr-archive-furnace',
    chapterId: 'chapter-5',
    primary: true,
    name: 'Kagura Archive Furnace',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '4,1', '5,1', '6,1', '7,1', '5,2', '6,2', '5,3', '6,3', '0,6', '1,6', '10,6', '11,6'],
    terrain: [
      { at: '3,2', tag: 'furnace-grate' },
      { at: '4,2', tag: 'furnace-grate' },
      { at: '7,2', tag: 'furnace-grate' },
      { at: '8,2', tag: 'furnace-grate' },
      { at: '3,4', tag: 'furnace-grate' },
      { at: '4,4', tag: 'furnace-grate' },
      { at: '7,4', tag: 'furnace-grate' },
      { at: '8,4', tag: 'furnace-grate' },
      { at: '2,3', tag: 'ash-field' },
      { at: '9,3', tag: 'ash-field' },
    ],
    hazards: [
      {
        id: 'forge-vent',
        trigger: 'bossTelegraph',
        tiles: ['3,2', '4,2', '7,2', '8,2', '3,4', '4,4', '7,4', '8,4'],
        effect: { type: 'damage', delivery: 'arcane', essence: 'ember', status: 'scorch', duration: 'one-command' },
        cue: 'Grates glow two pulses before the Forge Sermon resolves.',
      },
    ],
    spawn: { x: 2, y: 3, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'prison-locks', at: '10,3', destinationLevelId: 'kgr-prison-locks', condition: 'furnace-route-open' }],
    objective: 'Release the Furnace Abbot from the bell command, prevent its Forge Sermon from trapping the party, and open prison locks.',
    palette: ashPalette,
    interactables: [
      { id: 'forge-directives', at: '2,4', action: 'inspect-cipher', result: 'forge-directives-recorded' },
      { id: 'court-sigil-lock', at: '9,3', action: 'story', requires: 'mateus-burns-sigil' },
    ],
    lesson: 'Absorb and resist values matter; Frost terrain and Pierce exploit an overheated three-Recovery window.',
  },

  {
    id: 'kzu-public-tribunal',
    chapterId: 'chapter-6',
    primary: true,
    name: 'Kozui Public Tribunal',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '2,1', '3,1', '8,1', '9,1', '2,5', '3,5', '8,5', '9,5', '0,6', '1,6', '10,6', '11,6'],
    terrain: [
      { at: '4,2', tag: 'legal-seal' },
      { at: '7,2', tag: 'legal-seal' },
      { at: '4,4', tag: 'legal-seal' },
      { at: '7,4', tag: 'legal-seal' },
      { at: '1,3', tag: 'archive-floor' },
      { at: '10,3', tag: 'archive-floor' },
    ],
    hazards: [
      {
        id: 'seizure-order',
        trigger: 'bossTelegraph',
        dynamic: true,
        shape: { type: 'markedTiles', count: 2, selection: 'nearest-print-blocks' },
        effect: { type: 'objectiveDamage', target: 'print-block', amount: 1 },
        cue: 'Ujiro raises a vermilion writ over the chosen blocks one activation early.',
      },
    ],
    spawn: { x: 2, y: 3, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'canal-lock', at: '11,3', destinationLevelId: 'kzu-canal-lock', condition: 'three-print-blocks-preserved' }],
    objective: 'Disable Ujiro’s order actions and preserve three print blocks long enough for the bundles to leave.',
    palette: courtPalette,
    interactables: [
      { id: 'print-block-a', at: '1,3', action: 'defend', hp: 3 },
      { id: 'print-block-b', at: '2,4', action: 'defend', hp: 3 },
      { id: 'print-block-c', at: '2,2', action: 'defend', hp: 3 },
    ],
    lesson: 'Threat triage chooses between enemy damage, summoned clerks, and an objective with its own visible timer.',
  },

  {
    id: 'hsh-bell-aqueduct',
    chapterId: 'chapter-7',
    primary: true,
    name: 'Hushroad Bell Aqueduct',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '0,6', '1,6', '10,6', '11,6', '4,2', '7,2', '4,4', '7,4'],
    terrain: [
      { at: '2,1', tag: 'flowing-water' },
      { at: '3,1', tag: 'flowing-water' },
      { at: '8,1', tag: 'flowing-water' },
      { at: '9,1', tag: 'flowing-water' },
      { at: '2,5', tag: 'flowing-water' },
      { at: '3,5', tag: 'flowing-water' },
      { at: '8,5', tag: 'flowing-water' },
      { at: '9,5', tag: 'flowing-water' },
    ],
    hazards: [
      {
        id: 'prisoner-chain-lanes',
        trigger: 'bossTelegraph',
        dynamic: true,
        shape: { type: 'chainLine', count: 3, origin: 'warden' },
        effect: { type: 'bound', target: 'prisoner-token', countdownDelta: 1 },
        cue: 'Chains lock to a rescue space before the bell count advances.',
      },
    ],
    spawn: { x: 2, y: 3, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'prison-ferry', at: '11,3', destinationLevelId: 'hsh-prison-ferry', condition: 'all-prisoners-extracted' }],
    objective: 'Break chains, use swaps to occupy rescue spaces, and extract all prisoners before the fourth bell count.',
    palette: archivePalette,
    interactables: [
      { id: 'rescue-space-north', at: '2,1', action: 'extract-prisoner' },
      { id: 'rescue-space-south', at: '2,5', action: 'extract-prisoner' },
      { id: 'name-slip-water', at: '9,1', action: 'return-name-slip', result: 'release-bound-oni' },
    ],
    lesson: 'A tactical victory must include rescue; swaps are positional commitments, not free corrections.',
  },

  {
    id: 'c8-black-gate',
    chapterId: 'chapter-8',
    primary: true,
    name: 'Black Gate Causeway',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '0,6', '1,6', '10,6', '11,6', '5,2', '6,2', '5,3', '6,3', '5,4', '6,4'],
    terrain: [
      { at: '2,1', tag: 'ember-ash' },
      { at: '3,1', tag: 'ember-ash' },
      { at: '8,1', tag: 'umbral-ash' },
      { at: '9,1', tag: 'umbral-ash' },
      { at: '2,5', tag: 'umbral-ash' },
      { at: '3,5', tag: 'umbral-ash' },
      { at: '8,5', tag: 'ember-ash' },
      { at: '9,5', tag: 'ember-ash' },
      { at: '4,3', tag: 'dry-lantern' },
      { at: '7,3', tag: 'dry-lantern' },
    ],
    hazards: [
      {
        id: 'ash-lane-pair',
        trigger: 'bossTelegraph',
        dynamic: true,
        shape: { type: 'pairedZones', tags: ['ember-ash', 'umbral-ash'] },
        effect: { type: 'damage', essenceByTag: { 'ember-ash': 'ember', 'umbral-ash': 'umbral' } },
        cue: 'Lady Enma paints one orange and one violet lane before they ignite.',
      },
    ],
    spawn: { x: 2, y: 3, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'kurohana-gate', at: '11,3', destinationLevelId: 'krh-outer-archive', condition: 'ash-garrison-released' }],
    objective: 'Use each party role to stabilize hazard lanes, release the Ashen garrison, and open the Black Gate.',
    palette: courtPalette,
    interactables: [
      { id: 'lantern-relay-west', at: '4,3', action: 'signal', role: 'aya-or-kiku' },
      { id: 'lantern-relay-east', at: '7,3', action: 'signal', role: 'aya-or-kiku' },
    ],
    lesson: 'Late-game combinations use a small shared terrain grammar instead of six unrelated subsystems.',
  },

  {
    id: 'krh-observatory',
    chapterId: 'chapter-9',
    primary: true,
    name: 'Kurohana Throne Observatory',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '0,6', '1,6', '10,6', '11,6', '5,2', '6,2', '5,3', '6,3', '5,4', '6,4'],
    terrain: [
      { at: '2,1', tag: 'bell-node' },
      { at: '9,1', tag: 'bell-node' },
      { at: '2,5', tag: 'bell-node' },
      { at: '9,5', tag: 'bell-node' },
      { at: '4,3', tag: 'archive-floor' },
      { at: '7,3', tag: 'archive-floor' },
    ],
    hazards: [
      {
        id: 'yearless-ring',
        trigger: 'bossTelegraph',
        dynamic: true,
        shape: { type: 'ring', center: 'bell-core', radii: [2, 3] },
        effect: { type: 'damage', delivery: 'arcane', essence: 'umbral', status: 'dread', duration: 'one-activation' },
        cue: 'The bell core pulses through the next affected ring before it rings.',
      },
      {
        id: 'dawn-window',
        trigger: 'phaseChange',
        phase: 3,
        tiles: ['1,3', '2,3', '3,3'],
        effect: { type: 'temporaryWeakness', target: 'kurozane', essence: 'radiance', multiplier: 1.25 },
        cue: 'A pale teal break in the observatory roof arrives with daylight.',
      },
    ],
    spawn: { x: 2, y: 3, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'archive-evacuation', at: '11,3', destinationLevelId: 'epi-hoshigawa-archive', condition: 'kurozane-defeated-and-records-secured' }],
    objective: 'Break the final nodes, defeat Kurozane, and leave the archive evidence intact for public custody.',
    palette: courtPalette,
    interactables: [
      { id: 'north-node', at: '2,1', action: 'break-node' },
      { id: 'east-node', at: '9,1', action: 'break-node' },
      { id: 'south-node', at: '9,5', action: 'break-node' },
      { id: 'west-node', at: '2,5', action: 'break-node' },
    ],
    lesson: 'The final encounter recombines facing, recovery, elemental readouts, hazards, protection, and rescue without hiding the rules.',
  },

  {
    id: 'epi-hoshigawa-archive',
    chapterId: 'epilogue',
    primary: true,
    name: 'Hoshigawa Public Archive',
    kind: 'field',
    width: 20,
    height: 12,
    spacePx: 16,
    blocked: [
      '0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '6,0', '7,0', '8,0', '9,0', '10,0', '11,0', '12,0', '13,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0',
      '1,2', '2,2', '3,2', '4,2', '5,2', '14,2', '15,2', '16,2', '17,2', '18,2',
      '1,3', '5,3', '14,3', '18,3', '1,8', '5,8', '14,8', '18,8',
    ],
    terrain: [
      { at: '7,3', tag: 'archive-floor' },
      { at: '8,3', tag: 'archive-floor' },
      { at: '9,3', tag: 'archive-floor' },
      { at: '10,3', tag: 'archive-floor' },
      { at: '11,3', tag: 'archive-floor' },
      { at: '7,7', tag: 'archive-floor' },
      { at: '8,7', tag: 'archive-floor' },
      { at: '9,7', tag: 'archive-floor' },
      { at: '10,7', tag: 'archive-floor' },
      { at: '11,7', tag: 'archive-floor' },
    ],
    hazards: [],
    spawn: { x: 10, y: 10, facing: 'north', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'tower-road', at: '10,1', destinationLevelId: 'epi-takamine-tower', condition: 'testimony-table-opened' }],
    objective: 'Open a public testimony table with corrections allowed, then carry the final packet toward Takamine.',
    palette: { id: 'daybreak-parchment', shadow: '#263a45', ground: '#a58d65', accent: '#e1b85d', light: '#d8eee8' },
    interactables: [
      { id: 'testimony-table', at: '10,5', action: 'open', result: 'testimony-table-opened' },
      { id: 'corrections-shelf', at: '6,5', action: 'inspect', text: 'Corrections belong beside testimony, not beneath it.' },
      { id: 'unfiled-names', at: '13,5', action: 'listen', text: 'The archive marks what it does not yet know.' },
    ],
    lesson: 'The campaign closes with repair, listening, and correction—not a combat-shaped victory lap.',
  },
  {
    id: 'c1-flooded-cedars',
    chapterId: 'chapter-1',
    name: 'Flooded Cedar Route',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '0,1', '11,1', '3,2', '8,2', '0,6', '1,6', '10,6', '11,6'],
    terrain: [
      { at: '4,3', tag: 'shallow-puddle' },
      { at: '5,3', tag: 'shallow-puddle' },
      { at: '6,3', tag: 'shallow-puddle' },
      { at: '7,3', tag: 'shallow-puddle' },
      { at: '2,5', tag: 'dry-lantern' },
    ],
    hazards: [],
    spawn: { x: 4, y: 5, facing: 'north', formation: ['ren', 'aya'] },
    exits: [{ id: 'storehouse-trail', at: '11,3', destinationLevelId: 'c1-tax-storehouse', condition: 'route-encounters-cleared' }],
    objective: 'Learn the first Ledger reads among cedars before following the clerk trail to the storehouse.',
    palette: rainPalette,
    interactables: [{ id: 'dry-ledge-chest', at: '2,5', action: 'loot', optional: true, reward: 'River Salve' }],
    lesson: 'Cut resistance and Radiance weakness are introduced in adjacent, low-stakes authored fights.',
  },
  {
    id: 'sdg-rain-docks',
    chapterId: 'chapter-3',
    name: 'Sodegaura Rain Docks',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '0,6', '1,6', '10,6', '11,6', '4,1', '7,1', '4,5', '7,5'],
    terrain: [
      { at: '5,1', tag: 'storm-water' },
      { at: '6,1', tag: 'storm-water' },
      { at: '5,5', tag: 'storm-water' },
      { at: '6,5', tag: 'storm-water' },
      { at: '1,2', tag: 'dry-lantern' },
      { at: '1,5', tag: 'dry-lantern' },
    ],
    hazards: [
      {
        id: 'dock-patrol-hook-lane',
        trigger: 'enemyTelegraph',
        dynamic: true,
        shape: { type: 'line', length: 4, origin: 'retainer-facing' },
        effect: { type: 'pull', spaces: 2 },
        cue: 'A hook and its endpoint appear before the patrol can drag a witness.',
      },
    ],
    spawn: { x: 2, y: 4, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus'] },
    exits: [{ id: 'lantern-boat', at: '11,3', destinationLevelId: 'sdg-salt-warehouse', condition: 'witnesses-escorted' }],
    objective: 'Escort two witness tokens past a visible patrol route to the lantern boat.',
    palette: coastPalette,
    interactables: [{ id: 'lantern-boat-signal', at: '11,3', action: 'signal', requires: 'c3-lantern-route' }],
    lesson: 'A route choice produces a readable encounter, not a stealth fail state.',
  },
  {
    id: 'ngi-tide-caves',
    chapterId: 'chapter-4',
    name: 'Nagi Tide Caves',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '2,1', '9,1', '0,3', '11,3', '2,5', '9,5', '0,6', '1,6', '10,6', '11,6'],
    terrain: [
      { at: '4,1', tag: 'cold-pool' },
      { at: '5,1', tag: 'cold-pool' },
      { at: '6,1', tag: 'cold-pool' },
      { at: '7,1', tag: 'cold-pool' },
      { at: '4,5', tag: 'cold-pool' },
      { at: '5,5', tag: 'cold-pool' },
      { at: '6,5', tag: 'cold-pool' },
      { at: '7,5', tag: 'cold-pool' },
      { at: '2,3', tag: 'dry-lantern' },
    ],
    hazards: [
      {
        id: 'cold-wake-lane',
        trigger: 'enemyTelegraph',
        dynamic: true,
        shape: { type: 'trail', length: 3, origin: 'fog-skimmer' },
        effect: { type: 'status', status: 'chill', paceDeltaNextActivation: -1 },
        cue: 'A cyan wake shows the next three chilled spaces.',
      },
    ],
    spawn: { x: 2, y: 4, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'wreck-passage', at: '10,3', destinationLevelId: 'ngi-wrecked-carrack', condition: 'net-anchors-cleared' }],
    objective: 'Create dry lantern spaces through the cold pools and clear the net anchors.',
    palette: coastPalette,
    interactables: [{ id: 'net-anchor-a', at: '8,2', action: 'clear-fog' }, { id: 'net-anchor-b', at: '8,3', action: 'clear-fog' }, { id: 'net-anchor-c', at: '8,4', action: 'clear-fog' }],
    lesson: 'Elemental terrain is a concise, inspectable board state rather than simulated water physics.',
  },
  {
    id: 'kgr-ash-fields',
    chapterId: 'chapter-5',
    name: 'Kagura Ash Fields',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '0,6', '1,6', '10,6', '11,6', '4,1', '7,1', '4,5', '7,5'],
    terrain: [
      { at: '2,2', tag: 'ash-field' },
      { at: '3,2', tag: 'ash-field' },
      { at: '8,2', tag: 'ash-field' },
      { at: '9,2', tag: 'ash-field' },
      { at: '2,4', tag: 'ash-field' },
      { at: '3,4', tag: 'ash-field' },
      { at: '8,4', tag: 'ash-field' },
      { at: '9,4', tag: 'ash-field' },
      { at: '5,3', tag: 'flowing-water' },
      { at: '6,3', tag: 'flowing-water' },
    ],
    hazards: [],
    spawn: { x: 2, y: 3, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'furnace-road', at: '11,3', destinationLevelId: 'kgr-archive-furnace', condition: 'bound-oni-released' }],
    objective: 'Return a name slip to the flowing-water channel and release the Bound Ashen Oni.',
    palette: ashPalette,
    interactables: [{ id: 'name-slip', at: '6,2', action: 'carry' }, { id: 'release-channel', at: '5,3', action: 'return-name-slip' }],
    lesson: 'Nonlethal resolution is authored directly into a combat board objective.',
  },
  {
    id: 'kzu-archive-roof',
    chapterId: 'chapter-6',
    name: 'Kozui Archive Roof',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '0,6', '1,6', '10,6', '11,6', '5,0', '6,0', '5,6', '6,6'],
    terrain: [
      { at: '1,2', tag: 'archive-floor' },
      { at: '1,3', tag: 'archive-floor' },
      { at: '1,4', tag: 'archive-floor' },
      { at: '4,2', tag: 'legal-seal' },
      { at: '7,2', tag: 'legal-seal' },
      { at: '4,4', tag: 'legal-seal' },
      { at: '7,4', tag: 'legal-seal' },
    ],
    hazards: [
      {
        id: 'copy-seizure-mark',
        trigger: 'enemyTelegraph',
        dynamic: true,
        shape: { type: 'singleObjective', selection: 'least-protected' },
        effect: { type: 'objectiveDamage', amount: 1 },
        cue: 'A black writ stamps a print block or courier one activation before the clerk moves.',
      },
    ],
    spawn: { x: 3, y: 4, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'canal-rope', at: '11,3', destinationLevelId: 'kzu-public-tribunal', condition: 'copies-preserved' }],
    objective: 'Protect a civilian courier and three print blocks until the canal rope is available.',
    palette: courtPalette,
    interactables: [{ id: 'courier', at: '2,3', action: 'escort', hp: 3 }, { id: 'print-block-a', at: '1,2', action: 'defend', hp: 3 }, { id: 'print-block-b', at: '1,3', action: 'defend', hp: 3 }, { id: 'print-block-c', at: '1,4', action: 'defend', hp: 3 }],
    lesson: 'Multi-target pressure is readable because every intended objective target gets a direct marker.',
  },
  {
    id: 'hsh-prison-ferry',
    chapterId: 'chapter-7',
    name: 'Hushroad Prison Ferry',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '0,6', '1,6', '10,6', '11,6', '5,1', '6,1', '5,5', '6,5'],
    terrain: [
      { at: '2,1', tag: 'flowing-water' },
      { at: '3,1', tag: 'flowing-water' },
      { at: '8,1', tag: 'flowing-water' },
      { at: '9,1', tag: 'flowing-water' },
      { at: '2,5', tag: 'flowing-water' },
      { at: '3,5', tag: 'flowing-water' },
      { at: '8,5', tag: 'flowing-water' },
      { at: '9,5', tag: 'flowing-water' },
    ],
    hazards: [
      {
        id: 'ferry-chain-wall',
        trigger: 'enemyTelegraph',
        dynamic: true,
        shape: { type: 'front', length: 2, origin: 'bound-ashen-patrol' },
        effect: { type: 'status', status: 'bound', duration: 'one-activation' },
        cue: 'A chain is laid across the name-slip carrier’s route before it locks.',
      },
    ],
    spawn: { x: 2, y: 3, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'aqueduct-gate', at: '11,3', destinationLevelId: 'hsh-bell-aqueduct', condition: 'bound-patrol-released' }],
    objective: 'Carry and return a name slip to flowing water to open the aqueduct route.',
    palette: archivePalette,
    interactables: [{ id: 'carried-name-slip', at: '5,3', action: 'carry' }, { id: 'north-current', at: '2,1', action: 'return-name-slip' }],
    lesson: 'Swap is a deliberate position exchange with Recovery, useful when an objective carrier is bound.',
  },
  {
    id: 'krh-outer-archive',
    chapterId: 'chapter-9',
    name: 'Kurohana Outer Archive',
    kind: 'battle',
    width: 12,
    height: 7,
    spacePx: 32,
    blocked: ['0,0', '1,0', '10,0', '11,0', '0,6', '1,6', '10,6', '11,6', '5,2', '6,2', '5,3', '6,3', '5,4', '6,4'],
    terrain: [
      { at: '2,1', tag: 'bell-node' },
      { at: '9,1', tag: 'bell-node' },
      { at: '2,5', tag: 'bell-node' },
      { at: '9,5', tag: 'bell-node' },
      { at: '4,3', tag: 'archive-floor' },
      { at: '7,3', tag: 'archive-floor' },
    ],
    hazards: [
      {
        id: 'catalogue-line',
        trigger: 'enemyTelegraph',
        dynamic: true,
        shape: { type: 'line', length: 4, origin: 'archive-warden' },
        effect: { type: 'status', status: 'bound', duration: 'one-activation' },
        cue: 'Paper pages rise in a straight line before the binding order lands.',
      },
    ],
    spawn: { x: 2, y: 3, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'observatory-stair', at: '11,3', destinationLevelId: 'krh-observatory', condition: 'three-archive-nodes-broken' }],
    objective: 'Break key-locked archive nodes while keeping released spirit routes open.',
    palette: courtPalette,
    interactables: [{ id: 'archive-node-a', at: '2,1', action: 'break-node', requires: 'bell-key-1' }, { id: 'archive-node-b', at: '9,1', action: 'break-node', requires: 'bell-key-2' }, { id: 'archive-node-c', at: '9,5', action: 'break-node', requires: 'bell-key-3' }],
    lesson: 'The final dungeon’s objective language is a direct continuation of earlier rescue encounters.',
  },
  sceneHub({
    id: 'hsh-river-lane', chapterId: 'prologue', name: 'Hoshigawa River Lane', palette: rainPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0', '1,3', '2,3', '3,3', '14,3', '15,3', '16,3', '5,7', '6,7', '7,7'],
    terrain: [{ at: '10,10', tag: 'wet-stone' }, { at: '11,10', tag: 'wet-stone' }, { at: '12,10', tag: 'wet-stone' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren'] },
    exits: [{ id: 'census-square', at: '18,4', destinationLevelId: 'hsh-census-square', condition: 'medicine-delivered' }],
    objective: 'Carry Kiku’s medicine through the open side lane before the census bell rings.',
    interactables: [{ id: 'medicine-bottle', at: '3,8', action: 'receive' }, { id: 'mori-house-door', at: '13,4', action: 'deliver', requires: 'medicine-bottle' }, { id: 'blocked-cart', at: '6,7', action: 'inspect', text: 'The cart makes a clear detour rather than a collision trick.' }],
    lesson: 'The opening field route establishes exact movement and a small, human task.',
  }),
  sceneHub({
    id: 'hsh-riverbank', chapterId: 'prologue', name: 'Riverbank Escape Trail', palette: coastPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '0,8', '1,8', '2,8', '14,8', '15,8', '16,8', '5,5', '6,5', '12,4', '13,4'],
    terrain: [{ at: '3,7', tag: 'water' }, { at: '4,7', tag: 'water' }, { at: '5,7', tag: 'water' }, { at: '6,7', tag: 'water' }, { at: '7,7', tag: 'water' }, { at: '8,7', tag: 'water' }, { at: '9,7', tag: 'water' }, { at: '10,7', tag: 'water' }],
    spawn: { x: 2, y: 5, facing: 'east', formation: ['ren'] },
    exits: [{ id: 'archive-dawn', at: '18,3', destinationLevelId: 'c1-shrine-archive', condition: 'families-at-river' }],
    objective: 'Guide the escaping households along the marked river trail to dawn.',
    interactables: [{ id: 'river-checkpoint', at: '10,5', action: 'checkpoint', saves: true, restores: false }, { id: 'marked-doors-note', at: '13,3', action: 'record', result: 'hushigawa-doors-recorded' }],
    lesson: 'An escape route uses a checkpoint and visible water boundary, not a punishment loop.',
  }),
  sceneHub({
    id: 'c1-shrine-archive', chapterId: 'chapter-1', name: 'Hoshigawa Shrine Archive', palette: archivePalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0', '2,2', '3,2', '4,2', '15,2', '16,2', '17,2', '2,7', '3,7', '4,7', '15,7', '16,7', '17,7'],
    terrain: [{ at: '7,4', tag: 'archive-floor' }, { at: '8,4', tag: 'archive-floor' }, { at: '9,4', tag: 'archive-floor' }, { at: '10,4', tag: 'archive-floor' }, { at: '11,4', tag: 'archive-floor' }],
    spawn: { x: 9, y: 10, facing: 'north', formation: ['ren', 'aya'] },
    exits: [{ id: 'ferry-landing', at: '18,5', destinationLevelId: 'c1-ferry-landing', condition: 'records-compared' }],
    objective: 'Compare the household register, dispatch packet, and bell fragment impression.',
    interactables: [{ id: 'register-table', at: '9,4', action: 'compare-records', result: 'missing-household-marked' }, { id: 'casebook-shelf', at: '6,4', action: 'inspect', text: 'A casebook tracks people, not only evidence.' }],
    lesson: 'A hub can present investigation through placeable records rather than an exposition menu.',
  }),
  sceneHub({
    id: 'c1-ferry-landing', chapterId: 'chapter-1', name: 'Ferry Landing', palette: coastPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '6,6', '7,6', '8,6', '9,6', '10,6', '11,6', '12,6', '13,6'],
    terrain: [{ at: '6,7', tag: 'water' }, { at: '7,7', tag: 'water' }, { at: '8,7', tag: 'water' }, { at: '9,7', tag: 'water' }, { at: '10,7', tag: 'water' }, { at: '11,7', tag: 'water' }, { at: '12,7', tag: 'water' }, { at: '13,7', tag: 'water' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya'] },
    exits: [{ id: 'cedar-route', at: '18,3', destinationLevelId: 'c1-flooded-cedars', condition: 'three-conversations-complete' }],
    objective: 'Hear three local accounts, then follow the clerk trail through the flooded cedars.',
    interactables: [{ id: 'dock-worker', at: '5,4', action: 'talk', result: 'supply-manifest-lead' }, { id: 'ferry-captain', at: '10,4', action: 'talk', result: 'uphill-crates-lead' }, { id: 'market-seller', at: '14,4', action: 'talk', result: 'clerk-storehouse-lead' }],
    lesson: 'Multiple conversations distribute knowledge without a single authority figure solving the route.',
  }),
  sceneHub({
    id: 'sdg-market-lane', chapterId: 'chapter-3', name: 'Sodegaura Market Lane', palette: coastPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '3,3', '4,3', '7,3', '8,3', '12,3', '13,3', '15,7', '16,7'],
    terrain: [{ at: '5,8', tag: 'wet-stone' }, { at: '6,8', tag: 'wet-stone' }, { at: '7,8', tag: 'wet-stone' }],
    spawn: { x: 2, y: 9, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus'] },
    exits: [{ id: 'customs-house', at: '18,3', destinationLevelId: 'sdg-customs-house', condition: 'separate-arrivals-complete' }, { id: 'rain-docks', at: '18,8', destinationLevelId: 'sdg-rain-docks', condition: 'lantern-route-chosen' }],
    objective: 'Enter separately, gather trade context, and choose a lantern escort route.',
    interactables: [{ id: 'trade-broker', at: '6,4', action: 'talk', result: 'port-etiquette-note' }, { id: 'printer-stall', label: 'Sayo’s Print Stall', at: '10,4', action: 'talk', result: 'aya-printer-lead' }, { id: 'checkpoint-sign', at: '15,5', action: 'inspect', result: 'transport-mark-read' }],
    lesson: 'Port life is a hub of competing needs, not a flat faction backdrop.',
  }),
  sceneHub({
    id: 'sdg-customs-house', chapterId: 'chapter-3', name: 'Sodegaura Customs House', palette: courtPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0', '2,2', '3,2', '4,2', '15,2', '16,2', '17,2', '7,6', '8,6', '9,6', '10,6'],
    terrain: [{ at: '8,4', tag: 'archive-floor' }, { at: '9,4', tag: 'archive-floor' }, { at: '10,4', tag: 'archive-floor' }],
    spawn: { x: 2, y: 9, facing: 'north', formation: ['ren', 'aya', 'lise', 'mateus'] },
    exits: [{ id: 'dock-door', at: '18,5', destinationLevelId: 'sdg-rain-docks', condition: 'cipher-recorded' }],
    objective: 'Compare port ledger annotations and record Mateus’s admitted cipher handwriting.',
    interactables: [{ id: 'customs-ledger', at: '9,4', action: 'inspect-cipher', result: 'mateus-handwriting-recorded' }, { id: 'clerk-desk', at: '13,4', action: 'talk', result: 'port-clerk-witness' }],
    lesson: 'A character’s admission gives information without granting them instant trust.',
  }),
  sceneHub({
    id: 'ngi-fishing-village', chapterId: 'chapter-4', name: 'Nagi Fishing Village', palette: coastPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '2,3', '3,3', '4,3', '14,3', '15,3', '16,3', '2,8', '3,8', '4,8'],
    terrain: [{ at: '12,8', tag: 'water' }, { at: '13,8', tag: 'water' }, { at: '14,8', tag: 'water' }, { at: '15,8', tag: 'water' }, { at: '16,8', tag: 'water' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta'] },
    exits: [{ id: 'tide-caves', at: '18,3', destinationLevelId: 'ngi-tide-caves', condition: 'nagi-bargain-accepted' }],
    objective: 'Clear the bell-fog net route before asking fishers for passage.',
    interactables: [{ id: 'net-pile', at: '11,6', action: 'inspect', result: 'bell-fog-route' }, { id: 'kiku-remedy-basket', at: '6,5', action: 'talk', result: 'kiku-guest-support' }, { id: 'fisher-council', at: '14,4', action: 'bargain', result: 'nagi-bargain-accepted' }],
    lesson: 'Practical aid precedes requests for risk; the town sets the terms of its help.',
  }),
  sceneHub({
    id: 'ngi-wrecked-carrack', chapterId: 'chapter-4', name: 'Wrecked Carrack', palette: coastPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0', '5,3', '6,3', '7,3', '12,3', '13,3', '14,3', '5,7', '6,7', '7,7', '12,7', '13,7', '14,7'],
    terrain: [{ at: '3,9', tag: 'water' }, { at: '4,9', tag: 'water' }, { at: '15,9', tag: 'water' }, { at: '16,9', tag: 'water' }, { at: '9,4', tag: 'paper-litter' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'reef-deck', at: '18,4', destinationLevelId: 'ngi-storm-reef', condition: 'survivor-choice-complete' }],
    objective: 'Find the Varga journal, protect survivors, and choose Kiku’s initial rescue position.',
    interactables: [{ id: 'varga-journal', at: '9,4', action: 'read', result: 'varga-archive-truth' }, { id: 'survivor-hold', at: '15,5', action: 'choose-support', options: ['send-kiku', 'keep-kiku'] }, { id: 'reliquary-lock', label: 'Varga Strongbox', at: '11,5', action: 'inspect', result: 'second-key-lead' }],
    lesson: 'Heritage is evidence to examine, not a moral credential.',
  }),
  sceneHub({
    id: 'kgr-requisition-town', chapterId: 'chapter-5', name: 'Kagura Requisition Town', palette: ashPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '2,3', '3,3', '4,3', '14,3', '15,3', '16,3', '8,6', '9,6', '10,6'],
    terrain: [{ at: '6,8', tag: 'ash-field' }, { at: '7,8', tag: 'ash-field' }, { at: '8,8', tag: 'ash-field' }, { at: '9,8', tag: 'ash-field' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'ash-fields', at: '18,3', destinationLevelId: 'kgr-ash-fields', condition: 'requisition-marks-recorded' }],
    objective: 'Record the requisition marks and hear what refusing the furnace would cost local residents.',
    interactables: [{ id: 'coal-ledger', at: '8,4', action: 'record', result: 'requisition-marks-recorded' }, { id: 'resident-kitchen', at: '5,5', action: 'talk', result: 'coal-cost-testimony' }, { id: 'genta-supply-mark', at: '12,5', action: 'inspect', result: 'military-supply-chain-lead' }],
    lesson: 'The forge is sustained by named logistics and choices, not supernatural inevitability.',
  }),
  sceneHub({
    id: 'kgr-prison-locks', chapterId: 'chapter-5', name: 'Forge Prison Locks', palette: ashPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '2,2', '3,2', '5,2', '6,2', '8,2', '9,2', '11,2', '12,2', '2,7', '3,7', '5,7', '6,7', '8,7', '9,7', '11,7', '12,7'],
    terrain: [{ at: '14,5', tag: 'furnace-grate' }, { at: '15,5', tag: 'furnace-grate' }],
    spawn: { x: 2, y: 9, facing: 'north', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'furnace-door', at: '18,4', destinationLevelId: 'kgr-archive-furnace', condition: 'prison-route-chosen' }],
    objective: 'Choose a slower rescue route or faster blast route; neither choice is a hidden morality score.',
    interactables: [{ id: 'rescue-lock-panel', at: '7,4', action: 'choose-route', option: 'rescue' }, { id: 'blast-charge', at: '14,5', action: 'choose-route', option: 'blast' }],
    lesson: 'A route choice changes pacing and follow-up work, not whether named people deserve survival.',
  }),
  sceneHub({
    id: 'kzu-printmaker-lane', chapterId: 'chapter-6', name: 'Kozui Printmaker Lane', palette: courtPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '3,3', '4,3', '7,3', '8,3', '12,3', '13,3', '4,8', '5,8', '6,8'],
    terrain: [{ at: '9,5', tag: 'archive-floor' }, { at: '10,5', tag: 'archive-floor' }, { at: '11,5', tag: 'archive-floor' }],
    spawn: { x: 2, y: 9, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'tribunal', at: '18,3', destinationLevelId: 'kzu-public-tribunal', condition: 'three-copies-complete' }, { id: 'roof-run', at: '18,8', destinationLevelId: 'kzu-archive-roof', condition: 'clerks-pursue' }],
    objective: 'Complete woodblock, testimony packet, and boat-copy support tasks in any order.',
    interactables: [{ id: 'woodblock-bench', at: '5,4', action: 'support-task', result: 'woodblock-copy' }, { id: 'testimony-table', at: '10,4', action: 'support-task', result: 'testimony-copy' }, { id: 'boat-runner', at: '15,5', action: 'support-task', result: 'boat-copy' }],
    lesson: 'Player task order changes staging and allies, not the campaign’s core truth.',
  }),
  sceneHub({
    id: 'kzu-canal-lock', chapterId: 'chapter-6', name: 'Kozui Canal Lock', palette: coastPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '7,2', '8,2', '9,2', '7,3', '9,3', '7,4', '8,4', '9,4'],
    terrain: [{ at: '4,7', tag: 'water' }, { at: '5,7', tag: 'water' }, { at: '6,7', tag: 'water' }, { at: '10,7', tag: 'water' }, { at: '11,7', tag: 'water' }, { at: '12,7', tag: 'water' }],
    spawn: { x: 2, y: 9, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'hushroad-route', at: '18,3', destinationLevelId: 'hsh-map-table', condition: 'three-bundles-departed' }],
    objective: 'Send the three evidence bundles by separate routes before the canal lock opens.',
    interactables: [{ id: 'north-boat', at: '5,6', action: 'dispatch-copy', route: 'north' }, { id: 'central-courier', at: '10,5', action: 'dispatch-copy', route: 'center' }, { id: 'south-boat', at: '12,6', action: 'dispatch-copy', route: 'south' }],
    lesson: 'The story protects redundancy: evidence remains alive because no one copy bears the whole burden.',
  }),
  sceneHub({
    id: 'hsh-map-table', chapterId: 'chapter-7', name: 'Hushroad Map Table', palette: archivePalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '7,3', '8,3', '9,3', '10,3', '7,4', '8,4', '9,4', '10,4'],
    terrain: [{ at: '8,3', tag: 'archive-floor' }, { at: '9,3', tag: 'archive-floor' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'post-town', at: '18,3', destinationLevelId: 'hsh-post-town', condition: 'rescue-route-chosen' }],
    objective: 'Choose the rescue route over an early strike at Kurohana.',
    interactables: [{ id: 'hushroad-map', at: '9,4', action: 'story-choice', result: 'rescue-route-chosen' }, { id: 'prisoner-list', at: '6,4', action: 'inspect', result: 'prisoner-count-recorded' }],
    lesson: 'The chapter’s strategic choice refuses a calculation that writes prisoners off.',
  }),
  sceneHub({
    id: 'hsh-post-town', chapterId: 'chapter-7', name: 'Abandoned Post Town', palette: ashPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '2,3', '3,3', '4,3', '14,3', '15,3', '16,3', '7,7', '8,7', '9,7'],
    terrain: [{ at: '10,8', tag: 'ash-field' }, { at: '11,8', tag: 'ash-field' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'prison-ferry', at: '18,3', destinationLevelId: 'hsh-prison-ferry', condition: 'former-retainer-scene-complete' }],
    objective: 'Speak with Genta’s former subordinates and offer a concrete safe stand-down.',
    interactables: [{ id: 'former-retainer', at: '9,4', action: 'talk', result: 'former-retainer-scene-complete' }, { id: 'food-cache', at: '13,5', action: 'share-supplies', result: 'subordinate-food-route' }],
    lesson: 'Accountability allows people to refuse Genta while still making room for a practical choice.',
  }),
  sceneHub({
    id: 'c8-hoshigawa-return', chapterId: 'chapter-8', name: 'Hoshigawa Return', palette: rainPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '3,3', '4,3', '5,3', '14,3', '15,3', '16,3'],
    terrain: [{ at: '10,8', tag: 'wet-stone' }, { at: '11,8', tag: 'wet-stone' }],
    spawn: { x: 2, y: 9, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'black-gate-route', at: '18,3', destinationLevelId: 'c8-black-gate', condition: 'archive-runners-confirmed' }],
    objective: 'Ask Hoshigawa what it can safely contribute; archive runners are one optional concrete answer.',
    interactables: [{ id: 'archive-runner-table', at: '9,4', action: 'confirm-contribution', contribution: 'archive-runners' }, { id: 'evacuation-map', at: '13,4', action: 'inspect', text: 'The community sets its own risk and benefit.' }],
    lesson: 'Contribution is consent with visible risk, not a generic rebellion meter.',
  }),
  sceneHub({
    id: 'c8-sodegaura-return', chapterId: 'chapter-8', name: 'Sodegaura Return', palette: coastPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '3,3', '4,3', '14,3', '15,3', '5,7', '6,7', '7,7'],
    terrain: [{ at: '10,8', tag: 'water' }, { at: '11,8', tag: 'water' }, { at: '12,8', tag: 'water' }],
    spawn: { x: 2, y: 9, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'black-gate-route', at: '18,3', destinationLevelId: 'c8-black-gate', condition: 'evacuation-boats-confirmed' }],
    objective: 'Ask Sodegaura whether boats can support evacuation rather than assuming a military role.',
    interactables: [{ id: 'boat-council', at: '11,4', action: 'confirm-contribution', contribution: 'evacuation-boats' }, { id: 'dock-supplies', at: '6,5', action: 'inspect', text: 'The boats carry people first, not attack buffs.' }],
    lesson: 'The port’s contribution is a locally chosen evacuation route.',
  }),
  sceneHub({
    id: 'c8-takamine-return', chapterId: 'chapter-8', name: 'Takamine Return', palette: archivePalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '2,3', '3,3', '4,3', '14,3', '15,3', '16,3', '8,7', '9,7', '10,7'],
    terrain: [{ at: '11,8', tag: 'dry-lantern' }, { at: '12,8', tag: 'dry-lantern' }],
    spawn: { x: 2, y: 9, facing: 'east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'black-gate-route', at: '18,3', destinationLevelId: 'c8-black-gate', condition: 'medical-tents-confirmed' }],
    objective: 'Coordinate medical tents and a safe route with people who survived Takamine\'s experimental bell registry.',
    interactables: [{ id: 'medical-tent-list', at: '10,4', action: 'confirm-contribution', contribution: 'medical-tents' }, { id: 'lantern-route-map', at: '14,4', action: 'inspect', result: 'takamine-safe-route' }],
    lesson: 'No ally is converted into an anonymous assault bonus.',
  }),
  sceneHub({
    id: 'krh-audience-hall', chapterId: 'chapter-9', name: 'Kurohana Living Audience Hall', palette: courtPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '6,2', '7,2', '8,2', '9,2', '6,3', '9,3', '6,4', '8,4', '9,4'],
    terrain: [{ at: '4,4', tag: 'archive-floor' }, { at: '5,4', tag: 'archive-floor' }, { at: '7,4', tag: 'archive-floor' }, { at: '10,4', tag: 'archive-floor' }, { at: '11,4', tag: 'archive-floor' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'conservatory', at: '18,3', destinationLevelId: 'krh-blood-conservatory', condition: 'ujiro-custody-scene-complete' }],
    objective: 'Confront Ujiro’s last ledger and place him in public custody without destroying the evidence.',
    interactables: [{ id: 'ujiro-ledger', at: '8,3', action: 'confront-with-copies', result: 'ujiro-custody-scene-complete' }, { id: 'witness-circle', at: '5,4', action: 'talk', text: 'People harmed by the system take part in the custody decision.' }],
    lesson: 'The confrontation resolves through records and witnesses, not a stylish execution.',
  }),
  sceneHub({
    id: 'krh-blood-conservatory', chapterId: 'chapter-9', name: 'Kurohana Blood Conservatory', palette: courtPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '3,2', '4,2', '15,2', '16,2', '3,7', '4,7', '15,7', '16,7'],
    terrain: [{ at: '7,4', tag: 'umbral-ash' }, { at: '8,4', tag: 'umbral-ash' }, { at: '9,4', tag: 'umbral-ash' }, { at: '10,4', tag: 'umbral-ash' }, { at: '11,4', tag: 'umbral-ash' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'bell-spine', at: '18,3', destinationLevelId: 'krh-bell-spine', condition: 'six-offers-refused' }],
    objective: 'Let each hero refuse Kurozane’s tailored offer; the choice changes an opening readout, never the ending’s rejection.',
    interactables: [{ id: 'ren-offer', at: '6,4', action: 'refuse-offer', actor: 'ren' }, { id: 'aya-offer', at: '7,4', action: 'refuse-offer', actor: 'aya' }, { id: 'lise-offer', at: '8,4', action: 'refuse-offer', actor: 'lise' }, { id: 'mateus-offer', at: '9,4', action: 'refuse-offer', actor: 'mateus' }, { id: 'genta-offer', at: '10,4', action: 'refuse-offer', actor: 'genta' }, { id: 'kiku-offer', at: '11,4', action: 'refuse-offer', actor: 'kiku' }],
    lesson: 'Refusal is playable character ownership, not a branch where the story permits complicity.',
  }),
  sceneHub({
    id: 'krh-bell-spine', chapterId: 'chapter-9', name: 'Kurohana Bell Spine', palette: courtPalette,
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '5,2', '6,2', '7,2', '12,2', '13,2', '14,2', '5,7', '6,7', '7,7', '12,7', '13,7', '14,7'],
    terrain: [{ at: '9,3', tag: 'bell-node' }, { at: '10,3', tag: 'bell-node' }, { at: '9,4', tag: 'bell-node' }, { at: '10,4', tag: 'bell-node' }],
    hazards: [{ id: 'spine-pulse', trigger: 'cycle', periodMs: 3000, warningMs: 750, tiles: ['8,3', '9,3', '10,3', '11,3', '8,4', '9,4', '10,4', '11,4'], effect: { type: 'fieldDamage', percentMaxHp: 8, minimumHp: 1 }, cue: 'The lacquer veins brighten along the next pulse tiles.' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'observatory', at: '18,3', destinationLevelId: 'krh-observatory', condition: 'spine-nodes-broken' }],
    objective: 'Break the final spine nodes and reach the observatory without treating the castle as an abstract maze.',
    interactables: [{ id: 'spine-node-a', at: '9,3', action: 'break-node' }, { id: 'spine-node-b', at: '10,4', action: 'break-node' }],
    lesson: 'Even the final route uses declared pulse timing and recoverable field damage.',
  }),
  sceneHub({
    id: 'epi-sodegaura-storehouse', chapterId: 'epilogue', name: 'Sodegaura Medical Storehouse', palette: { id: 'daybreak-parchment', shadow: '#263a45', ground: '#a58d65', accent: '#e1b85d', light: '#d8eee8' },
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '15,0', '16,0', '17,0', '18,0', '19,0', '3,2', '4,2', '5,2', '14,2', '15,2', '16,2', '3,7', '4,7', '5,7', '14,7', '15,7', '16,7'],
    terrain: [{ at: '8,5', tag: 'archive-floor' }, { at: '9,5', tag: 'archive-floor' }, { at: '10,5', tag: 'archive-floor' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [{ id: 'takamine-tower-road', at: '18,3', destinationLevelId: 'epi-takamine-tower', condition: 'supplies-delivered' }],
    objective: 'Help Kiku deliver medical crates before the final lantern walk.',
    interactables: [{ id: 'medical-crate-a', at: '8,5', action: 'deliver-supplies' }, { id: 'medical-crate-b', at: '10,5', action: 'deliver-supplies' }, { id: 'genta-testimony-note', at: '13,4', action: 'inspect', text: 'Genta gives testimony before rebuilding a road.' }],
    lesson: 'The ending keeps practical care in player hands.',
  }),
  sceneHub({
    id: 'epi-takamine-tower', chapterId: 'epilogue', name: 'Repaired Takamine Tower', palette: { id: 'daybreak-parchment', shadow: '#263a45', ground: '#a58d65', accent: '#e1b85d', light: '#d8eee8' },
    blocked: ['0,0', '1,0', '2,0', '3,0', '4,0', '5,0', '6,0', '13,0', '14,0', '15,0', '16,0', '17,0', '18,0', '19,0', '2,3', '3,3', '4,3', '15,3', '16,3', '17,3', '7,2', '8,2', '11,2', '12,2'],
    terrain: [{ at: '9,3', tag: 'dry-lantern' }, { at: '10,3', tag: 'dry-lantern' }, { at: '9,4', tag: 'dry-lantern' }, { at: '10,4', tag: 'dry-lantern' }],
    spawn: { x: 2, y: 9, facing: 'north-east', formation: ['ren', 'aya', 'lise', 'mateus', 'genta', 'kiku'] },
    exits: [],
    objective: 'Deliver Ren’s final packet and light the lantern in the repaired tower. The bell does not ring.',
    interactables: [{ id: 'final-packet', at: '7,5', action: 'deliver', result: 'people-asking-after-one-another' }, { id: 'tower-lantern', at: '10,3', action: 'light', requires: 'final-packet-delivered', result: 'credits' }],
    lesson: 'The final image is a small lantern and a silent bell, not a claim that repair is complete.',
  }),
];

export function tileKey(x, y) {
  return `${x},${y}`;
}

export function parseTileKey(key) {
  const [x, y] = String(key).split(',').map(Number);
  return { x, y };
}

export function getLevel(id) {
  return LEVELS.find((level) => level.id === id) ?? null;
}

export function getLevelsForChapter(chapterId) {
  return LEVELS.filter((level) => level.chapterId === chapterId);
}

export function getLevelForChapter(chapterId) {
  const chapterLevels = getLevelsForChapter(chapterId);
  return chapterLevels.find((level) => level.primary) ?? chapterLevels[0] ?? null;
}

export function isInBounds(level, x, y) {
  return Boolean(level)
    && Number.isInteger(x)
    && Number.isInteger(y)
    && x >= 0
    && y >= 0
    && x < level.width
    && y < level.height;
}

export function isBlocked(level, x, y) {
  if (!isInBounds(level, x, y) || level.blocked.includes(tileKey(x, y))) return true;
  return getTerrainAt(level, x, y).some((tile) => TERRAIN_TAGS[tile.tag]?.passable === false);
}

export function getTerrainAt(level, x, y) {
  return level?.terrain.filter((tile) => tile.at === tileKey(x, y)) ?? [];
}

/** Lightweight authoring validation, useful to a browser boot check or tests. */
export function validateLevel(level) {
  const errors = [];
  if (!level?.id) errors.push('missing id');
  if (!Number.isInteger(level?.width) || !Number.isInteger(level?.height)) errors.push('invalid dimensions');
  for (const key of level?.blocked ?? []) {
    const { x, y } = parseTileKey(key);
    if (!isInBounds(level, x, y)) errors.push(`blocked tile outside grid: ${key}`);
  }
  for (const tile of level?.terrain ?? []) {
    const { x, y } = parseTileKey(tile.at);
    if (!isInBounds(level, x, y)) errors.push(`terrain tile outside grid: ${tile.at}`);
    if (!TERRAIN_TAGS[tile.tag]) errors.push(`unknown terrain tag: ${tile.tag}`);
  }
  if (!isInBounds(level, level?.spawn?.x, level?.spawn?.y)) errors.push('spawn outside grid');
  if (isBlocked(level, level?.spawn?.x, level?.spawn?.y)) errors.push('spawn is blocked');
  return errors;
}
