/**
 * Authored source for the Campaign Storyworld layer.
 *
 * The generated SweepWeave JSON and browser registry are derived from this
 * file by game/tools/build-storyworld.mjs.  The 60 canonical Campaign beats
 * remain save-stable; these ten clusters add thirty authored interstitial
 * scene nodes, twenty of which are experienced in a complete narrative run.
 */

export const STORYWORLD_SOURCE_VERSION = 1;
export const STORYWORLD_IFID = '7fd2f9d9-8d85-4f53-bcc9-7cb31ddd30d4';
export const STORYWORLD_CHARACTER_ID = 'char_lantern_network';

const property = (id, label, defaultValue) => Object.freeze({ id, label, defaultValue });

export const STORYWORLD_PROPERTIES = Object.freeze([
  property('proof_integrity', 'Proof integrity', 0.45),
  property('care_capacity', 'Care capacity', 0.50),
  property('network_consent', 'Network consent', 0.45),
  property('public_reach', 'Public reach', 0.35),
  property('route_safety', 'Route safety', 0.55),
  property('party_cohesion', 'Party cohesion', 0.50),
  property('mateus_accountability', 'Mateus accountability', 0.20),
  property('lise_oath_revision', 'Lise oath revision', 0.35),
  property('genta_accountability', 'Genta accountability', 0.30),
  property('aya_archive_openness', 'Aya archive openness', 0.45),
  property('ren_noncoercion', 'Ren noncoercion', 0.55),
  property('kiku_capacity', 'Kiku capacity', 0.50),
  property('witness_safety', 'Witness safety', 0.50),
  property('truth_completeness', 'Truth completeness', 0.40),
  property('court_pressure', 'Court pressure', 0.55),
  property('p_party_respects_limits', 'Belief: party respects limits', 0.45),
  property('p_mateus_truthfulness', 'Belief: Mateus tells the truth', 0.25),
]);

const reaction = (text, effects) => Object.freeze({ text, effects: Object.freeze({ ...effects }) });
const option = (id, text, gateProperty, accord, revision) => Object.freeze({
  id,
  text,
  gateProperty,
  accord: reaction(accord.text, accord.effects),
  revision: reaction(revision.text, revision.effects),
});
const outcome = (title, text, prompt, gateProperty, accord, revision) => Object.freeze({
  title,
  text,
  prompt,
  gateProperty,
  accord: reaction(accord.text, accord.effects),
  revision: reaction(revision.text, revision.effects),
});
const cluster = (definition) => Object.freeze({
  ...definition,
  options: Object.freeze(definition.options),
  relatedEncounterIds: Object.freeze(definition.relatedEncounterIds ?? []),
  accordOutcome: outcome(...definition.accordOutcome),
  revisionOutcome: outcome(...definition.revisionOutcome),
});

export const STORYWORLD_CLUSTERS = Object.freeze([
  cluster({
    id: 'sw1-clerks-second-copy',
    chapterId: 'chapter-1',
    anchorBeatId: 'c1-05-storehouse-clerk',
    placement: 'after-beat',
    sequenceRole: 'after-level-consequence',
    relatedEncounterIds: [],
    title: "The Clerk's Second Copy",
    text: "Rain ticks against the storehouse shutters while the clerk watches Aya compare two altered registers. The copy can expose a route through the Court's census machinery, but custody may endanger the person who made it. Ren asks the group to decide who may carry the evidence and what limit will make that custody answerable.",
    options: [
      option('leave-with-source', 'Leave the annotated copy with the clerk who made it.', 'ren_noncoercion',
        { text: 'The clerk hears a real offer rather than a test. He corrects two route marks himself, then sets the hour when Aya may return for a verified duplicate.', effects: { truth_completeness: 0.10, network_consent: 0.10, p_party_respects_limits: 0.10 } },
        { text: 'The clerk will not keep names beneath his roof. He does explain the inks and copying order, giving Aya a method she can corroborate without claiming his consent.', effects: { proof_integrity: 0.10, witness_safety: 0.10, ren_noncoercion: 0.05 } }),
      option('use-care-relay', "Send a bounded packet through Kiku's medicine route.", 'kiku_capacity',
        { text: 'Kiku accepts only the administrative packet and names each handoff. Care remains care, while the copied route reaches a second neighborhood without exposing a patient.', effects: { public_reach: 0.10, route_safety: 0.10, care_capacity: 0.05 } },
        { text: 'Kiku refuses to mix treatment with evidence custody. She still marks safe handoffs, and Ren records the refusal as a boundary rather than a failure.', effects: { witness_safety: 0.10, ren_noncoercion: 0.10, care_capacity: 0.05 } }),
      option('aya-indexed-hold', 'Let Aya hold it until she completes a public index.', 'aya_archive_openness',
        { text: 'Aya names a deadline, publishes the index structure, and gives the clerk a receipt. Temporary custody becomes visible work instead of an indefinite claim.', effects: { proof_integrity: 0.10, aya_archive_openness: 0.10, party_cohesion: 0.05 } },
        { text: 'Ren challenges a hold with no return condition. Aya accepts the correction, records the missing comparison as uncertain, and shortens her custody window.', effects: { truth_completeness: 0.10, ren_noncoercion: 0.10, party_cohesion: -0.05 } }),
    ],
    accordOutcome: [
      'Custody With a Clock',
      'The clerk writes the handoff time beside his own mark, making the limit legible to everyone in the room. Aya copies the condition before she copies another name. The party leaves with less control over the evidence, but with a stronger account of how it may travel without swallowing its source.',
      'State the limit that must accompany the copy.',
      'truth_completeness',
      { text: 'Aya reads the limit aloud, and the clerk corrects one word before accepting it. The revision becomes part of the evidence trail instead of private reassurance.', effects: { proof_integrity: 0.05, network_consent: 0.05, truth_completeness: 0.05 } },
      { text: 'The first wording still gives the party too much discretion. The clerk narrows it to one copy and one named handoff, and Ren accepts the smaller route.', effects: { witness_safety: 0.05, ren_noncoercion: 0.05, p_party_respects_limits: 0.05 } },
    ],
    revisionOutcome: [
      'Methods Without Names',
      'The clerk withholds every name that would make retaliation easy, yet he remains long enough to show how the false columns were built. Aya labels the testimony incomplete rather than weak. What survives is a reproducible method, a visible gap, and a civilian refusal the party must carry without rewriting it as consent.',
      'Record what the refusal still permits.',
      'witness_safety',
      { text: 'The group records ink, sequence, and count while leaving identities blank. The clerk sees that an incomplete archive can still tell the truth about its limits.', effects: { proof_integrity: 0.05, witness_safety: 0.05, aya_archive_openness: 0.05 } },
      { text: 'Aya nearly turns the absence into an inference. Kiku stops her, and the final note distinguishes what is unknown from what someone refused to surrender.', effects: { truth_completeness: 0.05, care_capacity: 0.05, ren_noncoercion: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw2-witness-not-family',
    chapterId: 'chapter-2',
    anchorBeatId: 'c2-06-name-from-europe',
    placement: 'after-beat',
    sequenceRole: 'after-boss-consequence',
    relatedEncounterIds: ['fp1-mateus'],
    title: 'Witness, Not Family',
    text: "Mateus has named the European cipher and admitted the hand that taught it to Kurozane's clerks. Lise recognizes a hunter's inheritance in the technique, but recognition does not make him kin and remorse does not make him safe. Freed prisoners wait beyond the stair while the party defines whether Mateus may speak, move, or advise.",
    options: [
      option('confined-witness', 'Treat Mateus as a confined, supervised witness.', 'mateus_accountability',
        { text: 'Mateus accepts a locked room, a visible guard, and no private audience. His first useful act is to name where confinement would endanger other prisoners.', effects: { mateus_accountability: 0.10, witness_safety: 0.10, p_mateus_truthfulness: 0.05 } },
        { text: 'He bargains for proximity to the records and is refused. Aya takes only his route facts, while Lise writes the attempted condition beside them.', effects: { truth_completeness: 0.10, mateus_accountability: 0.05, party_cohesion: -0.05 } }),
      option('bounded-consultant', 'Use him as a consultant with no command authority.', 'p_mateus_truthfulness',
        { text: 'Mateus translates one cipher, answers the exact questions asked, and stops. Aya can now test the result without allowing expertise to become control.', effects: { proof_integrity: 0.10, mateus_accountability: 0.10, party_cohesion: 0.05 } },
        { text: 'Aya catches an omitted handoff in his account. The omission enters the record, and every later answer will require independent corroboration.', effects: { truth_completeness: 0.10, p_mateus_truthfulness: -0.05, aya_archive_openness: 0.10 } }),
      option('survivor-terms', 'Ask the freed prisoners to set his permitted proximity.', 'network_consent',
        { text: 'The prisoners allow distant testimony but no shared room. Mateus accepts their terms, and the party arranges a relay that preserves both evidence and distance.', effects: { network_consent: 0.10, witness_safety: 0.10, mateus_accountability: 0.10 } },
        { text: 'They refuse his presence entirely. Mateus leaves written route facts and receives no answer, absolution, or restored authority in exchange.', effects: { ren_noncoercion: 0.10, truth_completeness: 0.10, mateus_accountability: 0.05 } }),
    ],
    accordOutcome: [
      'Terms of Distant Testimony',
      'A guard repeats the terms before Mateus speaks: no command, no private approach, no claim on forgiveness. He answers beneath those limits and corrects one location in the copied route. Lise watches for evasion; Aya watches the record; neither lets useful knowledge become a shortcut around the people who survived it.',
      'Choose what must be logged beside his testimony.',
      'mateus_accountability',
      { text: 'Aya records the harmful action, the later assistance, and the boundary between them. Mateus signs the sequence without asking the record to balance itself.', effects: { truth_completeness: 0.05, proof_integrity: 0.05, mateus_accountability: 0.05 } },
      { text: 'Mateus tries to explain motive before completing the sequence. Lise returns him to actions and omissions, preserving a usable account without granting interpretation control.', effects: { aya_archive_openness: 0.05, mateus_accountability: 0.05, p_mateus_truthfulness: -0.05 } },
    ],
    revisionOutcome: [
      'The Refusal Stands',
      "The survivors decline Mateus's presence, and the party does not negotiate on his behalf. His written cipher notes remain outside the room. The refusal changes the route and costs time, but it also makes clear that testimony can be useful without purchasing access to the people harmed by the witness.",
      'Carry the refusal into the route plan.',
      'ren_noncoercion',
      { text: 'Ren redraws the handoff around the survivors rather than around Mateus. The added distance becomes an explicit operational cost, not a complaint against their boundary.', effects: { route_safety: 0.05, witness_safety: 0.05, p_party_respects_limits: 0.05 } },
      { text: 'The first route still assumes a meeting at the final gate. Kiku removes it, and Aya labels the missing corroboration instead of concealing the gap.', effects: { care_capacity: 0.05, truth_completeness: 0.05, aya_archive_openness: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw3-sayos-warehouse-conditions',
    chapterId: 'chapter-3',
    anchorBeatId: 'c3-04-lantern-boat-escort',
    placement: 'before-beat',
    sequenceRole: 'before-boss-decision',
    relatedEncounterIds: ['c3-dock-patrol'],
    title: "Sayo's Warehouse Conditions",
    text: 'Sayo of Sodegaura has already divided prayer, household, and testimony routes so one seizure cannot expose them together. She meets the party as a local organizer, not a quest giver waiting for foreign expertise. The patrol tide is turning, carrier capacity is finite, and she requires the group to choose what moves first under her conditions.',
    options: [
      option('households-first', 'Move households before testimony.', 'p_party_respects_limits',
        { text: 'Sayo assigns the warehouse route because the party has followed limits before. Testimony waits while people move beyond the checkpoint in small groups.', effects: { witness_safety: 0.10, network_consent: 0.10, route_safety: 0.05 } },
        { text: 'Sayo refuses party escorts but accepts ordinary supplies. Ren records the smaller role, and the household route remains under local control.', effects: { care_capacity: 0.10, ren_noncoercion: 0.10, p_party_respects_limits: 0.05 } }),
      option('testimony-first', 'Move an independent testimony copy before households.', 'proof_integrity',
        { text: 'Because the copy can stand without its source names, Sayo permits one boat packet to leave. No household schedule is attached to it.', effects: { proof_integrity: 0.10, public_reach: 0.10, route_safety: 0.05 } },
        { text: 'The packet would expose the household route by timing alone. Sayo keeps it, and Aya records that publication has been delayed for safety.', effects: { witness_safety: 0.10, network_consent: 0.10, court_pressure: 0.05 } }),
      option('split-schedule', 'Keep the routes separate and let Sayo schedule both.', 'network_consent',
        { text: 'Sayo publishes bounded handoff windows to the people doing the carrying. The party supports both routes without merging their custody.', effects: { route_safety: 0.10, network_consent: 0.10, party_cohesion: 0.05 } },
        { text: 'Too few carriers make two routes impossible. Sayo chooses people first, and the evidence delay remains visible rather than blamed on the households.', effects: { care_capacity: 0.10, witness_safety: 0.10, public_reach: -0.05 } }),
    ],
    accordOutcome: [
      'Two Routes, Two Custodians',
      'The warehouse doors open on separate signals. Sayo names who owns each schedule and where the party must stop. Lise supplies patrol observations without choosing a route; Mateus remains outside the planning circle. The resulting plan is slower than a single heroic convoy and far harder for one capture to destroy.',
      'Confirm which authority can halt the movement.',
      'network_consent',
      { text: 'Sayo gives each route lead an independent stop signal. The party accepts that either signal can interrupt its preferred timing without further permission.', effects: { network_consent: 0.05, witness_safety: 0.05, route_safety: 0.05 } },
      { text: 'The party initially asks for a shared signal, concentrating authority again. Sayo divides it, and Ren repeats the corrected rule to every escort.', effects: { ren_noncoercion: 0.05, truth_completeness: 0.05, p_party_respects_limits: 0.05 } },
    ],
    revisionOutcome: [
      'Capacity Chooses the Order',
      'There are not enough trusted carriers for every plan. Sayo chooses the household movement and keeps the testimony copy under separate custody. Aya marks the publication delay and its reason. The scene ends without pretending scarcity has vanished, but also without turning local refusal into an obstacle for the heroes to overcome.',
      'Name the cost without assigning blame.',
      'truth_completeness',
      { text: 'Aya records the lost publication window, the preserved household route, and the exact capacity limit. The tradeoff remains legible to later readers.', effects: { truth_completeness: 0.05, aya_archive_openness: 0.05, witness_safety: 0.05 } },
      { text: 'The first record praises sacrifice and hides the burden. Kiku replaces it with numbers, names no victims, and keeps the missing capacity visible.', effects: { care_capacity: 0.05, proof_integrity: 0.05, public_reach: -0.05 } },
    ],
  }),
  cluster({
    id: 'sw4-margin-varga-journal',
    chapterId: 'chapter-4',
    anchorBeatId: 'c4-03-varga-journal',
    placement: 'after-beat',
    sequenceRole: 'after-level-consequence',
    relatedEncounterIds: [],
    title: 'A Margin in the Varga Journal',
    text: "The wreck has preserved a Varga journal page that links hunter knowledge to a sale network serving Kurozane's officers. Lise can read the family shorthand, but inherited expertise also implicates her house. Survivors retain the original while Aya asks what may travel onward and how delay, context, and custody will be made visible.",
    options: [
      option('publish-passage', 'Publish the incriminating passage immediately.', 'lise_oath_revision',
        { text: 'Lise supplies context without asking the record to defend her family. The passage travels with a note distinguishing inheritance from present consent.', effects: { truth_completeness: 0.10, public_reach: 0.10, lise_oath_revision: 0.10 } },
        { text: 'Lise argues from Varga authority, hears herself, and retracts it. Aya records both the passage and the attempted claim rather than smoothing the moment.', effects: { lise_oath_revision: 0.10, party_cohesion: -0.05, aya_archive_openness: 0.10 } }),
      option('copy-context', 'Copy the whole surrounding entry before release.', 'proof_integrity',
        { text: 'The surrounding pages expose the sale route and prevent one line from carrying more certainty than it can bear. Lise accepts the slower publication.', effects: { proof_integrity: 0.10, truth_completeness: 0.10, party_cohesion: 0.05 } },
        { text: 'Delay begins to resemble concealment. Lise accepts a public deadline, and Aya releases an index that names what remains under review.', effects: { aya_archive_openness: 0.10, lise_oath_revision: 0.10, public_reach: 0.05 } }),
      option('survivor-custody', 'Let wreck survivors decide what travels onward.', 'network_consent',
        { text: 'The survivors authorize an excerpt and retain the original. Their custody terms travel with every copy, limiting both Varga and party claims.', effects: { network_consent: 0.10, witness_safety: 0.10, lise_oath_revision: 0.10 } },
        { text: 'They refuse involvement beyond preserving the page. Aya records that boundary, and the party takes only an independent description of the find.', effects: { ren_noncoercion: 0.10, truth_completeness: 0.10, p_party_respects_limits: 0.05 } }),
    ],
    accordOutcome: [
      'An Inheritance Entered as Evidence',
      'Lise reads the family marks without claiming that blood grants custody. Aya places the Varga passage beside survivor terms and a visible chain of copies. The page becomes evidence of choices made by named institutions, not proof that foreign hunters were destined either to save Japan or corrupt it. That distinction remains attached.',
      'Choose the sentence that limits Varga authority.',
      'lise_oath_revision',
      { text: 'Lise writes that technical knowledge grants no right to command its use. The survivors approve the sentence and retain the original page.', effects: { lise_oath_revision: 0.05, network_consent: 0.05, truth_completeness: 0.05 } },
      { text: 'Her first sentence still centers family redemption. Aya removes it, and Lise replaces it with the concrete custody limit the survivors requested.', effects: { aya_archive_openness: 0.05, lise_oath_revision: 0.05, party_cohesion: -0.05 } },
    ],
    revisionOutcome: [
      'The Deadline Beside the Gap',
      'The page cannot yet be published without risking distortion or unwanted custody. Aya posts what is known, what is withheld, and when the decision will be reviewed. Lise accepts that transparency about delay is not the same as entitlement to the source, and the survivors keep control of the original.',
      'Record the delay without turning it into suspicion.',
      'aya_archive_openness',
      { text: 'Aya distinguishes absent context from concealed guilt and assigns the next review to a mixed custody group. The gap remains public and bounded.', effects: { aya_archive_openness: 0.05, proof_integrity: 0.05, network_consent: 0.05 } },
      { text: 'The first notice implies the survivors caused the delay. Ren corrects the wording, and Lise signs the change without defending the family claim.', effects: { ren_noncoercion: 0.05, lise_oath_revision: 0.05, p_party_respects_limits: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw5-cipher-handoff',
    chapterId: 'chapter-5',
    anchorBeatId: 'c5-05-sigil-burned',
    placement: 'before-beat',
    sequenceRole: 'before-boss-decision',
    relatedEncounterIds: ['c5-furnace-abbot'],
    title: 'The Cipher Handoff',
    text: "The cipher room turns people into numbered transfers between clerks, furnaces, and prison locks. Mateus understands the mechanism because he helped build an earlier form of it. Aya can reconstruct much from records, while a local clerk can map the ordinary process that the Court weaponized. The party must decide who explains first and who may correct whom.",
    options: [
      option('mateus-explains', 'Require Mateus to explain the cipher aloud.', 'mateus_accountability',
        { text: 'Mateus names each harmful handoff and the office that approved it. He does not hide people behind technical language or ask usefulness to settle his debt.', effects: { mateus_accountability: 0.10, truth_completeness: 0.10, proof_integrity: 0.05 } },
        { text: 'He retreats into mechanism and passive voice. Genta identifies the people hidden by the grammar, and Aya records the correction beside his account.', effects: { genta_accountability: 0.10, mateus_accountability: 0.05, truth_completeness: 0.10 } }),
      option('aya-explains', 'Have Aya explain only what the records corroborate.', 'proof_integrity',
        { text: 'Aya builds a complete enough chain to act on and labels every inference. Mateus answers only the narrow gaps she cannot resolve independently.', effects: { public_reach: 0.10, aya_archive_openness: 0.10, route_safety: 0.05 } },
        { text: 'Missing links stop the reconstruction. Aya asks Mateus bounded questions and marks each answer as testimony awaiting another independent source.', effects: { truth_completeness: 0.10, mateus_accountability: 0.05, proof_integrity: 0.05 } }),
      option('paired-process-map', "Pair Mateus's account with a local clerk's process map.", 'network_consent',
        { text: 'The clerk agrees to separate statements that can be compared later. The handoff chain becomes legible without forcing proximity or shared authority.', effects: { truth_completeness: 0.10, network_consent: 0.10, mateus_accountability: 0.05 } },
        { text: 'The clerk refuses any shared session with Mateus. Aya preserves the accounts separately and records the refusal as part of the method.', effects: { witness_safety: 0.10, ren_noncoercion: 0.10, proof_integrity: 0.05 } }),
    ],
    accordOutcome: [
      'A Chain With Human Verbs',
      'The reconstructed cipher now names who issued, copied, carried, and enforced each transfer. Technical precision remains, but it can no longer erase agency behind the mechanism. Mateus contributes knowledge under supervision; the local process remains authoritative where his memory conflicts with the records; Aya marks every unresolved edge for later review.',
      'Fix the handoff rule before opening the locks.',
      'truth_completeness',
      { text: 'Aya requires an action, an office, and a corroboration mark for every link. The rule exposes two weak points without pretending the chain is complete.', effects: { proof_integrity: 0.05, truth_completeness: 0.05, route_safety: 0.05 } },
      { text: 'One link still uses passive language that hides a guard unit. Genta supplies the missing verb and accepts that his own former unit belongs in the record.', effects: { genta_accountability: 0.05, aya_archive_openness: 0.05, mateus_accountability: 0.05 } },
    ],
    revisionOutcome: [
      'Separate Accounts, Shared Test',
      'No one is required to sit beside Mateus for the party to use what he knows. Aya separates his account from the clerk map and builds tests that either can fail. The added work costs time before the prison locks, yet it prevents the most powerful speaker from becoming the default interpreter.',
      'Choose the test that does not require trust.',
      'proof_integrity',
      { text: 'Aya compares transfer counts and time marks rather than motives. Both accounts can be checked without forcing either witness to endorse the other.', effects: { proof_integrity: 0.05, witness_safety: 0.05, p_mateus_truthfulness: 0.05 } },
      { text: 'The first test depends on a memory only Mateus controls. Lise rejects it, and the party substitutes a physical count from the lock mechanism.', effects: { lise_oath_revision: 0.05, truth_completeness: 0.05, route_safety: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw6-tribunal-afterword',
    chapterId: 'chapter-6',
    anchorBeatId: 'c6-03-tribunal',
    placement: 'after-beat',
    sequenceRole: 'after-boss-consequence',
    relatedEncounterIds: ['c6-ujiro'],
    title: 'Tribunal Afterword',
    text: "Mateus has admitted his part before a tribunal that cannot promise safety to every listener. The records prove some claims, contradict others, and leave dangerous omissions. Printers are already preparing copies while Kiku watches the exits. The party must decide whether corroboration, challenge, or immediate protection governs the next portion of testimony.",
    options: [
      option('corroborate-records', 'Corroborate only what the records presently prove.', 'proof_integrity',
        { text: 'Aya separates fact from confession and publishes the supported sequence. Mateus signs the limits, including one claim that remains explicitly unproven.', effects: { truth_completeness: 0.10, mateus_accountability: 0.10, public_reach: 0.10 } },
        { text: 'One claim outruns the documents. Aya marks it unproven in public, and Mateus loses the chance to use urgency as a substitute for support.', effects: { aya_archive_openness: 0.10, proof_integrity: 0.10, p_mateus_truthfulness: -0.05 } }),
      option('challenge-omissions', 'Challenge omissions before discussing motive.', 'mateus_accountability',
        { text: 'Mateus names the offices omitted from his first account without exposing victims. The added detail makes the institutional chain harder to deny.', effects: { mateus_accountability: 0.10, truth_completeness: 0.10, proof_integrity: 0.05 } },
        { text: 'He cannot answer one question without exposing living witnesses. The tribunal records the limit rather than treating silence as proof of innocence.', effects: { witness_safety: 0.10, mateus_accountability: 0.05, public_reach: -0.05 } }),
      option('move-listeners', 'Move threatened listeners before testimony continues.', 'kiku_capacity',
        { text: 'Kiku coordinates a second room and the account resumes under safer conditions. The delay becomes part of the public timeline.', effects: { witness_safety: 0.10, care_capacity: 0.10, mateus_accountability: 0.05 } },
        { text: 'No safe continuation is possible. Mateus accepts that urgency does not entitle him to an audience, and the printers release only supported records.', effects: { ren_noncoercion: 0.10, mateus_accountability: 0.05, party_cohesion: 0.05 } }),
    ],
    accordOutcome: [
      'Admission Under Corroboration',
      'The tribunal afterword travels as a layered record: proven sequence, bounded testimony, visible uncertainty, and listener conditions. Mateus is neither erased nor restored to authority. Printers can reproduce the evidence without reproducing his control over it, and threatened listeners remain able to set distance from the process and its later copies.',
      'Choose what the first print run must show.',
      'public_reach',
      { text: 'The printers place the corroborated chain beside its gaps and safety limits. Readers can distinguish what is known, claimed, and intentionally withheld.', effects: { public_reach: 0.05, proof_integrity: 0.05, witness_safety: 0.05 } },
      { text: 'The first layout centers Mateus because his account is dramatic. Aya and the printers reorganize it around actions, offices, and independent sources.', effects: { aya_archive_openness: 0.05, network_consent: 0.05, mateus_accountability: 0.05 } },
    ],
    revisionOutcome: [
      'An Audience Is Not Owed',
      "The account stops when safe conditions fail. Mateus receives no promise that everyone must hear him, and the missing continuation remains plainly marked. Kiku moves people before paper; Aya publishes only the supported portion; the party carries a less complete record that does not purchase completeness with another person's exposure.",
      'State why the account ended.',
      'witness_safety',
      { text: 'The public note names the safety condition without identifying those at risk. Ending the session becomes an accountable decision rather than a mysterious omission.', effects: { witness_safety: 0.05, truth_completeness: 0.05, public_reach: 0.05 } },
      { text: 'The first note blames disorder in the room. Kiku replaces it with the actual capacity limit and leaves no implication that listeners failed the tribunal.', effects: { care_capacity: 0.05, aya_archive_openness: 0.05, ren_noncoercion: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw7-soldier-will-not-follow',
    chapterId: 'chapter-7',
    anchorBeatId: 'c7-03-aqueduct-names',
    placement: 'before-beat',
    sequenceRole: 'before-boss-decision',
    relatedEncounterIds: ['c7-name-slip-release'],
    title: 'The Soldier Who Will Not Follow',
    text: "A former retainer refuses both Kurozane's order and Genta's invitation to join another command. The party still needs route facts, and the soldier's group still needs food and an unarmed exit map. Genta must decide whether assistance can remain assistance when no service, allegiance, confession, or later gratitude is promised.",
    options: [
      option('supplies-no-service', 'Leave food and an unarmed exit map without recruitment.', 'genta_accountability',
        { text: 'Genta makes the handoff without rank language. The soldiers accept ordinary supplies and preserve their refusal to serve either command.', effects: { genta_accountability: 0.10, route_safety: 0.10, p_party_respects_limits: 0.05 } },
        { text: 'They reject a handoff from Genta himself. Ren leaves the supplies at a neutral marker, and no one calls the refusal ingratitude.', effects: { ren_noncoercion: 0.10, care_capacity: 0.10, genta_accountability: 0.05 } }),
      option('facts-not-assistance', 'Ask for route facts, not assistance.', 'p_party_respects_limits',
        { text: 'One soldier identifies a closed ferry and nothing more. Genta repeats the fact without turning the speaker into a scout.', effects: { truth_completeness: 0.10, route_safety: 0.10, genta_accountability: 0.05 } },
        { text: 'The question still sounds like command. Genta withdraws it, and the party chooses a slower route without treating silence as betrayal.', effects: { genta_accountability: 0.10, ren_noncoercion: 0.10, route_safety: -0.05 } }),
      option('acknowledge-leave', 'Acknowledge the refusal and leave without another request.', 'ren_noncoercion',
        { text: 'The soldier later sends an unsolicited warning through a civilian courier. Because no obligation was claimed, the warning remains a choice.', effects: { genta_accountability: 0.10, witness_safety: 0.10, route_safety: 0.05 } },
        { text: 'No warning follows. The party does not reinterpret the silence, and Genta plans for uncertainty instead of demanding proof of loyalty.', effects: { truth_completeness: 0.10, ren_noncoercion: 0.10, route_safety: -0.05 } }),
    ],
    accordOutcome: [
      'Help Without a Banner',
      'Supplies change hands without recruitment and route facts remain bounded to what was freely offered. Genta does not recover honor by collecting followers. His repair begins in the smaller discipline of accepting a refusal, removing rank from his verbs, and planning around people who owe him nothing in return afterward.',
      'Name the rule Genta must carry forward.',
      'genta_accountability',
      { text: 'Genta states that need creates no command authority. He writes the rule on the route map where his old rank marks used to appear.', effects: { genta_accountability: 0.05, ren_noncoercion: 0.05, party_cohesion: 0.05 } },
      { text: 'His first rule still praises voluntary service. Ren removes the praise, and Genta replaces it with a plain record of supplies and boundaries.', effects: { truth_completeness: 0.05, genta_accountability: 0.05, p_party_respects_limits: 0.05 } },
    ],
    revisionOutcome: [
      'Silence Is Not Betrayal',
      'The former soldiers offer no route fact, warning, or future alliance. The party leaves supplies where they can be taken without meeting. Genta plans around the information gap and refuses the familiar story in which people outside his command must eventually prove themselves useful to him or his cause later.',
      'Mark the uncertainty on the route.',
      'truth_completeness',
      { text: 'The map shows an unverified ferry and no accusation. A slower path remains available, preserving movement without inventing a hostile motive.', effects: { truth_completeness: 0.05, route_safety: 0.05, ren_noncoercion: 0.05 } },
      { text: 'One note still labels the soldiers unreliable. Genta crosses it out, accepts the added risk, and records only that no information was offered.', effects: { genta_accountability: 0.05, aya_archive_openness: 0.05, route_safety: -0.05 } },
    ],
  }),
  cluster({
    id: 'sw8-boats-with-conditions',
    chapterId: 'chapter-8',
    anchorBeatId: 'c8-04-lantern-breach',
    placement: 'before-beat',
    sequenceRole: 'before-boss-decision',
    relatedEncounterIds: ['c8-outer-court'],
    title: 'Boats With Conditions',
    text: "Neighborhood boat crews will help breach Kurohana's isolation, but they refuse to become an unnamed rebel fleet. Their capacity belongs first to evacuation, and every additional bundle changes inspection risk. Ren presents three bounded plans while making clear that local leads can reject, revise, or stop any contribution without penalty.",
    options: [
      option('evacuation-only', 'Use the boats for evacuation only.', 'p_party_respects_limits',
        { text: 'The crews accept the clear boundary and refuse evidence cargo. Their boats remain under local leads, with the party supplying guards only when asked.', effects: { witness_safety: 0.10, route_safety: 0.10, network_consent: 0.10 } },
        { text: 'Ren keeps asking operational questions after the limit is stated. The lead repeats it, and he records the correction without seeking another opening.', effects: { ren_noncoercion: 0.10, truth_completeness: 0.10, p_party_respects_limits: 0.05 } }),
      option('one-sealed-bundle', 'Add one independently sealed record bundle.', 'route_safety',
        { text: 'Crews accept one finite addition because its custody and destination are independent of passenger lists. Aya removes every identity from the seal.', effects: { public_reach: 0.10, route_safety: 0.10, proof_integrity: 0.05 } },
        { text: 'The bundle changes inspection risk too sharply. Aya removes it, and no one treats evacuation as a lesser use of the boats.', effects: { witness_safety: 0.10, aya_archive_openness: 0.10, ren_noncoercion: 0.05 } }),
      option('reserve-local-choice', 'Hold one reserve boat for its local lead to assign.', 'network_consent',
        { text: 'The reserve responds to actual need without waiting for party approval. Its lead can choose evacuation, care, or withdrawal as conditions change.', effects: { care_capacity: 0.10, network_consent: 0.10, route_safety: 0.05 } },
        { text: 'Ambiguous responsibility makes reserve status unsafe. The lead commits the boat to evacuation now and removes it from every later plan.', effects: { truth_completeness: 0.10, witness_safety: 0.10, route_safety: 0.05 } }),
    ],
    accordOutcome: [
      'A Fleet With Many Owners',
      'The boats carry visible conditions instead of a single rebel banner. Each lead owns departure, passenger limits, and withdrawal. The party coordinates signals without absorbing those decisions into its command. Kurohana sees a network acting together, but not a population conscripted into the heroes\' preferred image of resistance or victory.',
      'Confirm who can cancel a departure.',
      'network_consent',
      { text: 'Every local lead retains unilateral cancellation authority. Ren repeats the rule over the signal line before the first boat moves.', effects: { network_consent: 0.05, route_safety: 0.05, p_party_respects_limits: 0.05 } },
      { text: 'The first signal plan requires central confirmation. A boat lead rejects it, and the party rewrites the signal so local cancellation is immediate.', effects: { ren_noncoercion: 0.05, witness_safety: 0.05, truth_completeness: 0.05 } },
    ],
    revisionOutcome: [
      'Evacuation Is Enough',
      'The crews reject evidence cargo and reserve ambiguity. Their contribution remains evacuation under local command, with no apology and no secret test of courage. Aya reroutes the archive bundle by land. The breach plan becomes less elegant and more honest about what each neighborhood actually consented to carry that night.',
      'Remove the rejected use from every later order.',
      'ren_noncoercion',
      { text: 'Ren strikes the cargo language from the route cards and names evacuation as the boats\' complete mission. No later commander may silently restore it.', effects: { ren_noncoercion: 0.05, witness_safety: 0.05, network_consent: 0.05 } },
      { text: 'A reserve note survives on one copied map. Aya recalls it, publishes the correction, and assigns the archive bundle to an independent land route.', effects: { aya_archive_openness: 0.05, proof_integrity: 0.05, route_safety: -0.05 } },
    ],
  }),
  cluster({
    id: 'sw9-mateus-living-archive',
    chapterId: 'chapter-9',
    anchorBeatId: 'c9-04-yearless-bell',
    placement: 'before-beat',
    sequenceRole: 'before-boss-decision',
    relatedEncounterIds: ['c9-yearless-bell'],
    title: 'Mateus at the Living Archive',
    text: "Kurozane's living archive contains cipher layers Mateus can read and witness boundaries he has no right to cross. The party may use his knowledge without restoring priestly, foreign, or scholarly authority. Aya asks whether he should translate aloud, write only a key, or remain silent until a local custodian requests an answer.",
    options: [
      option('translate-aloud', 'Have Mateus translate aloud while Aya records.', 'mateus_accountability',
        { text: 'Mateus distinguishes his original work from later alterations and stops whenever Aya asks. The translation remains a witnessed act, not his private edition.', effects: { truth_completeness: 0.10, mateus_accountability: 0.10, proof_integrity: 0.05 } },
        { text: 'He starts controlling interpretation through pace and omission. Aya stops the session, records the attempt, and keeps only independently checked lines.', effects: { aya_archive_openness: 0.10, mateus_accountability: 0.05, p_mateus_truthfulness: -0.05 } }),
      option('cipher-key-only', 'Ask him to write only a bounded cipher key.', 'witness_safety',
        { text: 'The key permits independent reading later without bringing Mateus near witnesses. He labels where context is missing and claims no final interpretation.', effects: { proof_integrity: 0.10, witness_safety: 0.10, mateus_accountability: 0.05 } },
        { text: 'The key is incomplete without context. Mateus labels that limit instead of expanding his access, and Aya preserves the unfinished tool.', effects: { truth_completeness: 0.10, aya_archive_openness: 0.10, public_reach: -0.05 } }),
      option('wait-for-custodian', 'Keep him silent unless a local custodian asks.', 'network_consent',
        { text: 'Mateus accepts silence and follows guard instructions. A custodian later asks one narrow question, which he answers carefully in writing.', effects: { mateus_accountability: 0.10, network_consent: 0.10, party_cohesion: 0.05 } },
        { text: 'He volunteers a warning before being asked. The guard stops him; he submits it in writing and accepts that urgency does not erase the rule.', effects: { truth_completeness: 0.10, mateus_accountability: 0.05, p_mateus_truthfulness: -0.05 } }),
    ],
    accordOutcome: [
      'Knowledge Under Revocable Terms',
      'Mateus contributes a bounded key whose use can be stopped, checked, and reassigned. Aya and local custodians retain interpretation authority. His change of heart appears as costly restraint and useful testimony, not absolution, restored office, or a claim that European knowledge must lead the resistance or define its future direction.',
      'State what Mateus does not receive in return.',
      'mateus_accountability',
      { text: 'The record grants no command, pardon, private access, or restored title. Mateus signs the limits before the key enters local custody.', effects: { mateus_accountability: 0.05, network_consent: 0.05, truth_completeness: 0.05 } },
      { text: 'One draft thanks him in language that implies restoration. Lise removes it, and the final receipt records only the bounded work completed.', effects: { lise_oath_revision: 0.05, aya_archive_openness: 0.05, party_cohesion: 0.05 } },
    ],
    revisionOutcome: [
      'The Translation Stops',
      "Aya ends the session when Mateus begins to control interpretation. The archive keeps the checked lines, the attempted omission, and the unfinished cipher key. He remains available under guard, but usefulness does not entitle him to continue. The party enters Kurozane's final chamber with a narrower and more trustworthy record.",
      'Preserve the stopped boundary in the archive.',
      'aya_archive_openness',
      { text: 'Aya timestamps the halt and separates verified lines from abandoned interpretation. Later readers can see why the account ends where it does.', effects: { aya_archive_openness: 0.05, proof_integrity: 0.05, witness_safety: 0.05 } },
      { text: 'The first copy omits the attempted control. Lise restores the note, refusing to make Mateus easier to forgive by making the record smoother.', effects: { lise_oath_revision: 0.05, truth_completeness: 0.05, p_mateus_truthfulness: -0.05 } },
    ],
  }),
  cluster({
    id: 'sw10-corrections-desk',
    chapterId: 'epilogue',
    anchorBeatId: 'e00-open-archive',
    placement: 'after-beat',
    sequenceRole: 'after-level-consequence',
    relatedEncounterIds: [],
    title: 'The Corrections Desk',
    text: "The open archive receives disputed names, harmful wording, incomplete testimony, and requests to remove records that still expose living people. Aya cannot repair every entry at once. The final Storyworld decision determines how corrections remain visible, who controls testimony beside a disputed line, and how capacity limits are published without becoming another closed door.",
    options: [
      option('annotate-errors', 'Annotate errors without silently erasing the original entry.', 'aya_archive_openness',
        { text: 'Readers can see both the harmful record and its correction under controlled access. Survivors retain authority over when the original wording may be viewed.', effects: { aya_archive_openness: 0.10, proof_integrity: 0.10, public_reach: 0.05 } },
        { text: 'A survivor objects that preservation still repeats harm. The desk restricts the original and publishes only the correction plus a reason for the limit.', effects: { network_consent: 0.10, witness_safety: 0.10, aya_archive_openness: 0.05 } }),
      option('testimony-beside', 'Place authorized testimony beside the disputed entry.', 'network_consent',
        { text: 'The contradiction remains visible because witnesses authorized publication. Their words are not treated as decoration around the old official record.', effects: { truth_completeness: 0.10, public_reach: 0.10, network_consent: 0.10 } },
        { text: 'Authorization is absent. The desk records that testimony exists without exposing it, preserving the gap and the witness boundary together.', effects: { witness_safety: 0.10, aya_archive_openness: 0.10, proof_integrity: 0.05 } }),
      option('contested-queue', 'Open a public queue for contested records and review dates.', 'care_capacity',
        { text: 'Unresolved claims receive visible dates, named custodians, and published capacity limits. Delay becomes accountable work instead of another quiet disappearance.', effects: { public_reach: 0.10, aya_archive_openness: 0.10, network_consent: 0.05 } },
        { text: 'The queue exceeds capacity on its first day. Aya posts the limit, pays local reviewers, and names the next date without promising impossible speed.', effects: { truth_completeness: 0.10, care_capacity: 0.10, public_reach: 0.05 } }),
    ],
    accordOutcome: [
      'Corrections Remain Visible',
      'The desk opens with visible review dates, controlled access, and testimony published only under its custodians\' terms. Aya does not promise a pure archive. She promises that correction, refusal, delay, and uncertainty will leave accountable traces. The party\'s victory becomes an institution people can revise rather than another perfect record imposed from above.',
      'The narrative route closes on an archive that can be corrected without erasing who set each boundary.',
      'truth_completeness',
      { text: 'Aya enters the final correction with its source, custodian, review date, and visibility limit. The archive remains open because its authority can be challenged.', effects: { truth_completeness: 0.05, aya_archive_openness: 0.05, network_consent: 0.05 } },
      { text: 'The first final entry still sounds complete. Aya adds the unresolved questions and leaves space for the next custodian to change her work.', effects: { proof_integrity: 0.05, public_reach: 0.05, ren_noncoercion: 0.05 } },
    ],
    revisionOutcome: [
      'The Limit Is Posted',
      'The corrections desk cannot review every claim or expose every source safely. Aya publishes the capacity limit, the missing authorizations, and the next review date. The archive remains imperfect without pretending imperfection is neutral. Repair begins as visible, revisable labor shared with the people whose names the old ledger tried to own.',
      'The narrative route closes with limits named plainly instead of hidden behind institutional language.',
      'aya_archive_openness',
      { text: 'The posted limit includes who set it, who may challenge it, and when it expires. Delay becomes a condition that can be contested rather than a permanent silence.', effects: { aya_archive_openness: 0.05, truth_completeness: 0.05, public_reach: 0.05 } },
      { text: 'The first notice offers no path to challenge. Ren and Kiku add a local review handoff, and Aya signs the correction to her own procedure.', effects: { ren_noncoercion: 0.05, care_capacity: 0.05, network_consent: 0.05 } },
    ],
  }),
]);
