/**
 * Authored source for the Campaign Storyworld layer.
 *
 * The generated SweepWeave JSON and browser registry are derived from this
 * file by game/tools/build-storyworld.mjs.  The 60 canonical Campaign beats
 * remain save-stable; these eleven clusters add thirty-five authored
 * interstitial scene nodes, twenty-two of which are experienced in a complete
 * narrative run.
 */

export const STORYWORLD_SOURCE_VERSION = 3;
export const STORYWORLD_IFID = '7fd2f9d9-8d85-4f53-bcc9-7cb31ddd30d4';
export const STORYWORLD_CHARACTER_ID = 'char_lantern_network';

const property = (id, label, defaultValue) => Object.freeze({ id, label, defaultValue });

export const STORYWORLD_PROPERTIES = Object.freeze([
  property('proof_integrity', 'Proof integrity', 0.45),
  property('care_capacity', 'Care capacity', 0.50),
  property('network_consent', 'Network consent', 0.45),
  property('public_reach', 'Public reach', 0.35),
  property('route_safety', 'Route safety', 0.55),
  property('party_cohesion', 'Party cohesion', 0.50),
  property('mateus_accountability', 'Mateus accountability', 0.20),
  // Save-compatible legacy key: this now measures Nikola's earned discipline
  // and surrender of inherited command claims, not the superseded character.
  property('lise_oath_revision', 'Nikola severed-command discipline', 0.35),
  property('genta_accountability', 'Genta accountability', 0.30),
  property('aya_archive_openness', 'Aya archive openness', 0.45),
  property('ren_noncoercion', 'Ren noncoercion', 0.55),
  property('kiku_capacity', 'Kiku capacity', 0.50),
  property('witness_safety', 'Witness safety', 0.50),
  property('truth_completeness', 'Truth completeness', 0.40),
  property('court_pressure', 'Court pressure', 0.55),
  property('p_party_respects_limits', 'Belief: party respects limits', 0.45),
  property('p_mateus_truthfulness', 'Belief: Mateus tells the truth', 0.25),
  property('enma_custody', 'Lady Enma held in rotating custody', 0),
  property('enma_killed', 'Lady Enma killed at the Black Gate', 0),
  property('enma_compact', 'Lady Enma bound by a witnessed defection compact', 0),
  property('enma_testimony', 'Lady Enma testimony reliability', 0.30),
  property('act3_salt_priority', 'Act III priority: Salt Road', 0),
  property('act3_ash_priority', 'Act III priority: Ash Road', 0),
  property('act3_paper_priority', 'Act III priority: Paper Road', 0),
  property('salt_commitment', 'Salt-road coalition commitment', 0.20),
  property('ash_commitment', 'Ash-road coalition commitment', 0.20),
  property('paper_commitment', 'Paper-road coalition commitment', 0.20),
  property('evacuation_capacity', 'Evacuation capacity', 0.20),
  property('oni_supply_disruption', 'Oni supply disruption', 0.10),
  property('succession_readiness', 'Civil succession readiness', 0.10),
  property('bell_intelligence', 'Bell-network intelligence', 0.10),
  property('garrison_defection', 'Garrison defection readiness', 0.10),
]);

const reaction = (text, effects, outcomeKey = undefined) => Object.freeze({
  text,
  effects: Object.freeze({ ...effects }),
  ...(outcomeKey ? { outcomeKey } : {}),
});
const option = (id, text, gateProperty, accord, revision) => Object.freeze({
  id,
  text,
  gateProperty,
  accord: reaction(accord.text, accord.effects, accord.outcomeKey),
  revision: reaction(revision.text, revision.effects, revision.outcomeKey),
});
const outcome = (title, text, prompt, gateProperty, accord, revision) => Object.freeze({
  title,
  text,
  prompt,
  gateProperty,
  accord: reaction(accord.text, accord.effects),
  revision: reaction(revision.text, revision.effects),
});
const cluster = (definition) => Object.freeze({
  ...definition,
  options: Object.freeze(definition.options),
  relatedEncounterIds: Object.freeze(definition.relatedEncounterIds ?? []),
  entryRouteEffects: Object.freeze({ ...(definition.entryRouteEffects ?? {}) }),
  outcomeRouteEffects: Object.freeze({ ...(definition.outcomeRouteEffects ?? {}) }),
  accordOutcome: outcome(...definition.accordOutcome),
  revisionOutcome: outcome(...definition.revisionOutcome),
  ...(definition.thirdOutcome ? { thirdOutcome: outcome(...definition.thirdOutcome) } : {}),
});

const actIntegration = (actId, majorSequenceId, role, routeTheater = null) => Object.freeze({
  actId,
  majorSequenceId,
  role,
  routeTheater,
});

export const STORYWORLD_ACT_INTEGRATION = Object.freeze({
  'sw3-sayos-warehouse-conditions': actIntegration('act-iii', 'act3-sequence-01', 'route-decision'),
  'sw4-margin-varga-journal': actIntegration('act-iii', 'act3-operation-nagi', 'route-operation', 'salt'),
  'sw5-cipher-handoff': actIntegration('act-iii', 'act3-operation-kagura', 'route-operation', 'ash'),
  'sw6-tribunal-afterword': actIntegration('act-iii', 'act3-operation-kozui', 'route-operation', 'paper'),
  'sw7-soldier-will-not-follow': actIntegration('act-iii', 'act3-sequence-07', 'fixed-emergency', 'ash'),
  'sw8-boats-with-conditions': actIntegration('act-iv', 'act4-sequence-04', 'approach-consequence', 'salt'),
  'sw-enma-three-terms': actIntegration('act-iv', 'act4-sequence-07', 'gate-boss-consequence'),
  'sw9-mateus-living-archive': actIntegration('act-v', 'act5-living-archive', 'inner-castle-decision'),
  'sw10-corrections-desk': actIntegration('act-v', 'act5-last-command', 'final-political-consequence'),
});

export const STORYWORLD_CLUSTERS = Object.freeze([
  cluster({
    id: 'sw1-clerks-second-copy',
    chapterId: 'chapter-1',
    anchorBeatId: 'c1-05-storehouse-clerk',
    placement: 'after-beat',
    sequenceRole: 'after-level-consequence',
    relatedEncounterIds: [],
    title: "The Clerk's Second Copy",
    text: "Rain ticks against the storehouse shutters while the clerk watches Aya compare two altered registers. The copy can expose a route through the Court's census machinery, but custody may endanger the person who made it. Ren asks the group to decide who may carry the evidence and what limit will make that custody answerable.",
    options: [
      option('leave-with-source', 'Leave the annotated copy with the clerk who made it.', 'ren_noncoercion',
        { text: 'The clerk hears a real offer rather than a test. He corrects two route marks himself, then sets the hour when Aya may return for a verified duplicate.', effects: { truth_completeness: 0.10, network_consent: 0.10, p_party_respects_limits: 0.10 } },
        { text: 'The clerk will not keep names beneath his roof. He does explain the inks and copying order, giving Aya a method she can corroborate without claiming his consent.', effects: { proof_integrity: 0.10, witness_safety: 0.10, ren_noncoercion: 0.05 } }),
      option('use-care-relay', "Send a bounded packet through Kiku's medicine route.", 'kiku_capacity',
        { text: 'Kiku accepts only the administrative packet and names each handoff. Care remains care, while the copied route reaches a second neighborhood without exposing a patient.', effects: { public_reach: 0.10, route_safety: 0.10, care_capacity: 0.05 } },
        { text: 'Kiku refuses to mix treatment with evidence custody. She still marks safe handoffs, and Ren records the refusal as a boundary rather than a failure.', effects: { witness_safety: 0.10, ren_noncoercion: 0.10, care_capacity: 0.05 } }),
      option('aya-indexed-hold', 'Let Aya hold it until she completes a public index.', 'aya_archive_openness',
        { text: 'Aya names a deadline, publishes the index structure, and gives the clerk a receipt. Temporary custody becomes visible work instead of an indefinite claim.', effects: { proof_integrity: 0.10, aya_archive_openness: 0.10, party_cohesion: 0.05 } },
        { text: 'Ren challenges a hold with no return condition. Aya accepts the correction, records the missing comparison as uncertain, and shortens her custody window.', effects: { truth_completeness: 0.10, ren_noncoercion: 0.10, party_cohesion: -0.05 } }),
    ],
    accordOutcome: [
      'Custody With a Clock',
      'The clerk writes the handoff time beside his own mark, making the limit legible to everyone in the room. Aya copies the condition before she copies another name. The party leaves with less control over the evidence, but with a stronger account of how it may travel without swallowing its source.',
      'State the limit that must accompany the copy.',
      'truth_completeness',
      { text: 'Aya reads the limit aloud, and the clerk corrects one word before accepting it. The revision becomes part of the evidence trail instead of private reassurance.', effects: { proof_integrity: 0.05, network_consent: 0.05, truth_completeness: 0.05 } },
      { text: 'The first wording still gives the party too much discretion. The clerk narrows it to one copy and one named handoff, and Ren accepts the smaller route.', effects: { witness_safety: 0.05, ren_noncoercion: 0.05, p_party_respects_limits: 0.05 } },
    ],
    revisionOutcome: [
      'Methods Without Names',
      'The clerk withholds every name that would make retaliation easy, yet he remains long enough to show how the false columns were built. Aya labels the testimony incomplete rather than weak. What survives is a reproducible method, a visible gap, and a civilian refusal the party must carry without rewriting it as consent.',
      'Record what the refusal still permits.',
      'witness_safety',
      { text: 'The group records ink, sequence, and count while leaving identities blank. The clerk sees that an incomplete archive can still tell the truth about its limits.', effects: { proof_integrity: 0.05, witness_safety: 0.05, aya_archive_openness: 0.05 } },
      { text: 'Aya nearly turns the absence into an inference. Kiku stops her, and the final note distinguishes what is unknown from what someone refused to surrender.', effects: { truth_completeness: 0.05, care_capacity: 0.05, ren_noncoercion: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw2-witness-not-family',
    chapterId: 'chapter-2',
    anchorBeatId: 'c2-06-name-from-europe',
    placement: 'after-beat',
    sequenceRole: 'after-boss-consequence',
    relatedEncounterIds: ['fp1-mateus'],
    title: 'Witness, Not Family',
    text: "Mateus has named the European cipher and admitted that he translated the Dracul precedent for Kurozane's clerks. Lord Nikola Dra\u017eani\u0107 recognizes both Adriatic merchant marks and the Severed Dragon counter-ward his house says its Wallachian forebears carried west. Shared Latin and a European route make the two men useful to one another, not kin, and remorse does not make Mateus safe. Freed prisoners wait beyond the stair while the party defines whether he may speak, move, or advise.",
    options: [
      option('confined-witness', 'Treat Mateus as a confined, supervised witness.', 'mateus_accountability',
        { text: 'Mateus accepts a locked room, a visible guard, and no private audience. His first useful act is to name where confinement would endanger other prisoners.', effects: { mateus_accountability: 0.10, witness_safety: 0.10, p_mateus_truthfulness: 0.05 } },
        { text: 'He bargains for proximity to the records and is refused. Aya takes only his route facts, while Nikola writes the attempted condition beside them and, for once, does not add his borrowed title.', effects: { truth_completeness: 0.10, mateus_accountability: 0.05, party_cohesion: -0.05 } }),
      option('bounded-consultant', 'Use him as a consultant with no command authority.', 'p_mateus_truthfulness',
        { text: 'Mateus translates one cipher, answers the exact questions asked, and stops. Aya can now test the result without allowing expertise to become control.', effects: { proof_integrity: 0.10, mateus_accountability: 0.10, party_cohesion: 0.05 } },
        { text: 'Aya catches an omitted handoff in his account. The omission enters the record, and every later answer will require independent corroboration.', effects: { truth_completeness: 0.10, p_mateus_truthfulness: -0.05, aya_archive_openness: 0.10 } }),
      option('survivor-terms', 'Ask the freed prisoners to set his permitted proximity.', 'network_consent',
        { text: 'The prisoners allow distant testimony but no shared room. Mateus accepts their terms, and the party arranges a relay that preserves both evidence and distance.', effects: { network_consent: 0.10, witness_safety: 0.10, mateus_accountability: 0.10 } },
        { text: 'They refuse his presence entirely. Mateus leaves written route facts and receives no answer, absolution, or restored authority in exchange.', effects: { ren_noncoercion: 0.10, truth_completeness: 0.10, mateus_accountability: 0.05 } }),
    ],
    accordOutcome: [
      'Terms of Distant Testimony',
      'A guard repeats the terms before Mateus speaks: no command, no private approach, no claim on forgiveness. He answers beneath those limits and corrects one location in the copied route. Nikola follows the Latin for evasion; Aya governs the record and decides what is relevant. Neither man is allowed to turn foreign knowledge into a shortcut around the people who survived it.',
      'Choose what must be logged beside his testimony.',
      'mateus_accountability',
      { text: 'Aya records the harmful action, the later assistance, and the boundary between them. Mateus signs the sequence without asking the record to balance itself.', effects: { truth_completeness: 0.05, proof_integrity: 0.05, mateus_accountability: 0.05 } },
      { text: 'Mateus tries to explain motive before completing the sequence. Nikola cuts across him in formal Latin; Aya cuts across both men and returns the account to actions and omissions, preserving evidence without granting either foreigner interpretation control.', effects: { aya_archive_openness: 0.05, mateus_accountability: 0.05, p_mateus_truthfulness: -0.05 } },
    ],
    revisionOutcome: [
      'The Refusal Stands',
      "The survivors decline Mateus's presence, and the party does not negotiate on his behalf. His written cipher notes remain outside the room. The refusal changes the route and costs time, but it also makes clear that testimony can be useful without purchasing access to the people harmed by the witness.",
      'Carry the refusal into the route plan.',
      'ren_noncoercion',
      { text: 'Ren redraws the handoff around the survivors rather than around Mateus. The added distance becomes an explicit operational cost, not a complaint against their boundary.', effects: { route_safety: 0.05, witness_safety: 0.05, p_party_respects_limits: 0.05 } },
      { text: 'The first route still assumes a meeting at the final gate. Kiku removes it, and Aya labels the missing corroboration instead of concealing the gap.', effects: { care_capacity: 0.05, truth_completeness: 0.05, aya_archive_openness: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw3-sayos-warehouse-conditions',
    chapterId: 'chapter-3',
    anchorBeatId: 'c3-01-separate-arrivals',
    placement: 'before-beat',
    sequenceRole: 'act-route-decision',
    relatedEncounterIds: [],
    title: 'The Bellless House War Table',
    text: "Rain maps three ways north across the Bellless House floor. Sayo's salt boats can move households and testimony without merging their custody. Kagura's furnace route can starve the Oni collars of ash and blood. Kozui's printers can prepare governors, garrisons, and towns to survive a transfer of power. The coalition has time to finish only three of four regional operations before Kurozane closes the roads. Ren asks which road receives the first signal, resources, and political promise.",
    options: [
      option('salt-road-first', "Back Sayo's Salt Road: boats, households, and separated testimony routes.", 'network_consent',
        { text: 'Sayo accepts the first signal because her boat leads keep cancellation authority. The coalition commits escorts and stores without taking command of either civilian route.', outcomeKey: 'accord', effects: { act3_salt_priority: 0.10, salt_commitment: 0.10, evacuation_capacity: 0.05 } },
        { text: 'Sayo rejects a single coalition timetable, then accepts a narrower promise of supplies. Her refusal changes the plan without changing the chosen Salt Road priority.', outcomeKey: 'accord', effects: { act3_salt_priority: 0.10, salt_commitment: 0.05, ren_noncoercion: 0.10 } }),
      option('ash-road-first', "Back Kagura's Ash Road: break the collar furnaces before the Oni muster.", 'court_pressure',
        { text: 'The coalition assigns saboteurs to the ash fields and rescue crews to the locks. Destroying production, not conscripted bodies, becomes the first military objective.', outcomeKey: 'revision', effects: { act3_ash_priority: 0.10, ash_commitment: 0.10, oni_supply_disruption: 0.05 } },
        { text: 'Kagura cannot promise a clean strike, but the table accepts her warning and funds prisoner routes beside sabotage. The Ash Road remains first without pretending its cost is solved.', outcomeKey: 'revision', effects: { act3_ash_priority: 0.10, ash_commitment: 0.05, witness_safety: 0.10 } }),
      option('paper-road-first', "Back Kozui's Paper Road: publish the transfer case before taking the palace.", 'proof_integrity',
        { text: 'Aya divides the blocks among independent printers while Kozui delegates prepare provisional offices. The first victory sought is a country able to receive surrendered seals.', outcomeKey: 'negotiated', effects: { act3_paper_priority: 0.10, paper_commitment: 0.10, succession_readiness: 0.05 } },
        { text: 'Several delegates refuse a manifesto written by the party. Aya accepts their revisions, and the Paper Road begins as a distributed argument rather than a foreign proclamation.', outcomeKey: 'negotiated', effects: { act3_paper_priority: 0.10, paper_commitment: 0.05, public_reach: 0.10 } }),
    ],
    accordOutcome: [
      'Salt Before Steel',
      "Sayo lays separate blue cords for households, testimony, and the armed escort. Nikola offers to command the boats; she tells him his useful place is reading patrol formations and obeying local stop signals. He does. Mateus recognizes a blood-census mark and gives it to Aya without entering the custody circle. Sodegaura will receive the first coalition resources, making evacuation and independent evidence routes stronger when the palace closes the coast.",
      'Set the Salt Road condition that no commander may overrule.',
      'network_consent',
      { text: 'Every boat lead retains an immediate stop signal, even if delay costs the coalition its preferred operation. Ren writes the rule onto the military route card.', effects: { salt_commitment: 0.05, evacuation_capacity: 0.05, network_consent: 0.05 } },
      { text: 'Nikola asks for an emergency exception and withdraws it when Sayo names who would bear the risk. The corrected order leaves cancellation local and visible.', effects: { salt_commitment: 0.05, lise_oath_revision: 0.05, witness_safety: 0.05 } },
    ],
    revisionOutcome: [
      'Ash Before the Muster',
      "Kagura marks furnaces, prison locks, and the paths by which bound Oni are fed into Kurozane's garrisons. Ren refuses a plan that counts every collared soldier as a target. Rescue lanes and sabotage therefore share the same clock, slowing the strike but denying the court both weapons and fresh servants. The Ash Road receives the first coalition resources, and Kurozane's counterstroke will come through requisition towns and bell wardens rather than the coast.",
      'State what destruction must spare.',
      'witness_safety',
      { text: 'The order protects prison locks, name slips, water routes, and every worker who can be separated from a collar. Only production nodes receive demolition marks.', effects: { ash_commitment: 0.05, oni_supply_disruption: 0.05, witness_safety: 0.05 } },
      { text: 'A broad furnace symbol would also burn the prisoner passage. Ren splits the target, accepting a harder attack that preserves the release route.', effects: { ash_commitment: 0.05, party_cohesion: 0.05, ren_noncoercion: 0.05 } },
    ],
    thirdOutcome: [
      'Paper Before the Throne',
      "Kozui's printers reject a proclamation authored by victorious foreigners and rebuild it as questions every district must answer: who holds grain, who may order a garrison, how a blood command is proved ended, and who can remove a provisional keeper. Aya distributes blocks that disagree in wording but share an inventory. The Paper Road receives the first coalition resources, preparing institutions that can accept Kurozane's seals without simply handing them to his killer.",
      'Name the authority the printed plan cannot create by itself.',
      'succession_readiness',
      { text: 'The blocks can publish procedures and evidence, but only participating towns and offices can confer provisional authority. Aya prints that limit beside every proposed transfer.', effects: { paper_commitment: 0.05, succession_readiness: 0.05, aya_archive_openness: 0.05 } },
      { text: 'Nikola asks whether his covenant can guarantee the transfer. The printers answer that it can restrain a vampire, not appoint a government, and he accepts the distinction.', effects: { paper_commitment: 0.05, lise_oath_revision: 0.05, network_consent: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw4-margin-varga-journal',
    chapterId: 'chapter-4',
    anchorBeatId: 'c4-03-varga-journal',
    placement: 'after-beat',
    sequenceRole: 'after-level-consequence',
    relatedEncounterIds: [],
    entryRouteEffects: { salt_commitment: 0.05 },
    outcomeRouteEffects: { bell_intelligence: 0.05 },
    // The ids above remain stable for existing campaign bindings. Their visible
    // scene is now the Severed Dragon house testament and Nikola's
    // rank/complicity arc; the old ids remain save-compatible.
    title: 'A Margin in the Severed Dragon Testament',
    text: "The wreck has preserved a Dra\u017eani\u0107 testament page and the marriage contracts hidden behind its boast of an unbroken male line. Wallachian wardcraft, the Croatian house name, land, and an English Wychmere dowry repeatedly passed through noblewomen whose marriages exchanged refuge, ships, money, or armed protection. Later titled Dra\u017eani\u0107 men converted the public check on immortal rule into hereditary purge authority. Nikola can read the household abbreviations, but his mixed ancestry and claimed rank implicate rather than vindicate him. The wreck survivors retain the original while Aya asks what may travel onward.",
    options: [
      option('publish-passage', 'Publish the incriminating passage immediately.', 'lise_oath_revision',
        { text: 'Nikola supplies context without asking the record to rescue his house. The passage travels with a note naming each woman as an actor and distinguishing inherited liability from his present choices.', effects: { truth_completeness: 0.10, public_reach: 0.10, lise_oath_revision: 0.10 } },
        { text: 'Nikola invokes the authority of a count he never legally was and calls the women links in his line. Aya makes him retract both claims, preserving the passage and his attempted use of rank.', effects: { lise_oath_revision: 0.10, party_cohesion: -0.05, aya_archive_openness: 0.10 } }),
      option('copy-context', 'Copy the whole surrounding entry before release.', 'proof_integrity',
        { text: 'The surrounding pages expose the sale route and prevent one line from carrying more certainty than it can bear. Nikola accepts the slower publication despite the injury to his house name.', effects: { proof_integrity: 0.10, truth_completeness: 0.10, party_cohesion: 0.05 } },
        { text: 'Delay begins to resemble noble concealment. Nikola accepts a public deadline, and Aya releases an index that names what remains under review.', effects: { aya_archive_openness: 0.10, lise_oath_revision: 0.10, public_reach: 0.05 } }),
      option('survivor-custody', 'Let wreck survivors decide what travels onward.', 'network_consent',
        { text: 'The survivors authorize an excerpt and retain the original. Their custody terms travel with every copy, limiting Dra\u017eani\u0107, mercantile, and party claims alike.', effects: { network_consent: 0.10, witness_safety: 0.10, lise_oath_revision: 0.10 } },
        { text: 'They refuse involvement beyond preserving the page. Aya records that boundary, and the party takes only an independent description of the find.', effects: { ren_noncoercion: 0.10, truth_completeness: 0.10, p_party_respects_limits: 0.05 } }),
    ],
    accordOutcome: [
      'A Covenant Entered as Evidence',
      'Nikola reads the family marks and his English mother\'s contract without claiming that blood, covenant technique, or an inflated title grants custody. Aya places the Severed Dragon passage beside survivor terms and a visible chain of copies. The page becomes evidence that women carried a house men falsely advertised as patrilineal, and that a check on emergency power can itself become hereditary power. It is not proof that a foreign hunter was destined either to save Japan or corrupt it. That distinction remains attached.',
      'Choose the sentence that limits Nikola\'s inherited authority.',
      'lise_oath_revision',
      { text: 'Nikola writes that wardcraft and noble birth grant no right to command their use; the pattern may divide blood from office, never appoint the hunter as successor. The survivors approve the sentence and retain the original.', effects: { lise_oath_revision: 0.05, network_consent: 0.05, truth_completeness: 0.05 } },
      { text: 'His first sentence still centers restoration of the Dra\u017eani\u0107 name. Aya removes it, and Nikola replaces it with the concrete custody limit the survivors requested.', effects: { aya_archive_openness: 0.05, lise_oath_revision: 0.05, party_cohesion: -0.05 } },
    ],
    revisionOutcome: [
      'The Deadline Beside the Gap',
      'The page cannot yet be published without risking distortion or unwanted custody. Aya posts what is known, what is withheld, and when the decision will be reviewed. Nikola accepts that transparency about delay is not the same as a gentleman\'s entitlement to the source, and the survivors keep control of the original.',
      'Record the delay without turning it into suspicion.',
      'aya_archive_openness',
      { text: 'Aya distinguishes absent context from concealed guilt and assigns the next review to a mixed custody group. The gap remains public and bounded.', effects: { aya_archive_openness: 0.05, proof_integrity: 0.05, network_consent: 0.05 } },
      { text: 'The first notice implies the survivors caused the delay. Ren corrects the wording, and Nikola signs the change without defending his family claim or styling himself Count.', effects: { ren_noncoercion: 0.05, lise_oath_revision: 0.05, p_party_respects_limits: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw5-cipher-handoff',
    chapterId: 'chapter-5',
    anchorBeatId: 'c5-05-sigil-burned',
    placement: 'before-beat',
    sequenceRole: 'before-boss-decision',
    relatedEncounterIds: ['c5-furnace-abbot'],
    entryRouteEffects: { ash_commitment: 0.05 },
    outcomeRouteEffects: { oni_supply_disruption: 0.05 },
    title: 'The Cipher Handoff',
    text: "The cipher room turns people into numbered transfers between clerks, furnaces, and prison locks. Mateus understands the mechanism because he helped build an earlier form of it. Aya can reconstruct much from records, while a local clerk can map the ordinary process that the Court weaponized. The party must decide who explains first and who may correct whom.",
    options: [
      option('mateus-explains', 'Require Mateus to explain the cipher aloud.', 'mateus_accountability',
        { text: 'Mateus names each harmful handoff and the office that approved it. He does not hide people behind technical language or ask usefulness to settle his debt.', effects: { mateus_accountability: 0.10, truth_completeness: 0.10, proof_integrity: 0.05 } },
        { text: 'He retreats into mechanism and passive voice. Genta identifies the people hidden by the grammar, and Aya records the correction beside his account.', effects: { genta_accountability: 0.10, mateus_accountability: 0.05, truth_completeness: 0.10 } }),
      option('aya-explains', 'Have Aya explain only what the records corroborate.', 'proof_integrity',
        { text: 'Aya builds a complete enough chain to act on and labels every inference. Mateus answers only the narrow gaps she cannot resolve independently.', effects: { public_reach: 0.10, aya_archive_openness: 0.10, route_safety: 0.05 } },
        { text: 'Missing links stop the reconstruction. Aya asks Mateus bounded questions and marks each answer as testimony awaiting another independent source.', effects: { truth_completeness: 0.10, mateus_accountability: 0.05, proof_integrity: 0.05 } }),
      option('paired-process-map', "Pair Mateus's account with a local clerk's process map.", 'network_consent',
        { text: 'The clerk agrees to separate statements that can be compared later. The handoff chain becomes legible without forcing proximity or shared authority.', effects: { truth_completeness: 0.10, network_consent: 0.10, mateus_accountability: 0.05 } },
        { text: 'The clerk refuses any shared session with Mateus. Aya preserves the accounts separately and records the refusal as part of the method.', effects: { witness_safety: 0.10, ren_noncoercion: 0.10, proof_integrity: 0.05 } }),
    ],
    accordOutcome: [
      'A Chain With Human Verbs',
      'The reconstructed cipher now names who issued, copied, carried, and enforced each transfer. Technical precision remains, but it can no longer erase agency behind the mechanism. Mateus contributes knowledge under supervision; the local process remains authoritative where his memory conflicts with the records; Aya marks every unresolved edge for later review.',
      'Fix the handoff rule before opening the locks.',
      'truth_completeness',
      { text: 'Aya requires an action, an office, and a corroboration mark for every link. The rule exposes two weak points without pretending the chain is complete.', effects: { proof_integrity: 0.05, truth_completeness: 0.05, route_safety: 0.05 } },
      { text: 'One link still uses passive language that hides a guard unit. Genta supplies the missing verb and accepts that his own former unit belongs in the record.', effects: { genta_accountability: 0.05, aya_archive_openness: 0.05, mateus_accountability: 0.05 } },
    ],
    revisionOutcome: [
      'Separate Accounts, Shared Test',
      'No one is required to sit beside Mateus for the party to use what he knows. Aya separates his account from the clerk map and builds tests that either can fail. The added work costs time before the prison locks, yet it prevents the most powerful speaker from becoming the default interpreter.',
      'Choose the test that does not require trust.',
      'proof_integrity',
      { text: 'Aya compares transfer counts and time marks rather than motives. Both accounts can be checked without forcing either witness to endorse the other.', effects: { proof_integrity: 0.05, witness_safety: 0.05, p_mateus_truthfulness: 0.05 } },
      { text: 'The first test depends on a memory only Mateus controls. Nikola distrusts the priest\'s word; Aya rejects Nikola\'s honor test as equally private, and the party substitutes a physical count from the lock mechanism.', effects: { lise_oath_revision: 0.05, truth_completeness: 0.05, route_safety: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw6-tribunal-afterword',
    chapterId: 'chapter-6',
    anchorBeatId: 'c6-03-tribunal',
    placement: 'after-beat',
    sequenceRole: 'after-boss-consequence',
    relatedEncounterIds: ['c6-ujiro'],
    entryRouteEffects: { paper_commitment: 0.05 },
    outcomeRouteEffects: { succession_readiness: 0.05 },
    title: 'Tribunal Afterword',
    text: "Mateus has admitted his part before a tribunal that cannot promise safety to every listener. The records prove some claims, contradict others, and leave dangerous omissions. Printers are already preparing copies while Kiku watches the exits. The party must decide whether corroboration, challenge, or immediate protection governs the next portion of testimony.",
    options: [
      option('corroborate-records', 'Corroborate only what the records presently prove.', 'proof_integrity',
        { text: 'Aya separates fact from confession and publishes the supported sequence. Mateus signs the limits, including one claim that remains explicitly unproven.', effects: { truth_completeness: 0.10, mateus_accountability: 0.10, public_reach: 0.10 } },
        { text: 'One claim outruns the documents. Aya marks it unproven in public, and Mateus loses the chance to use urgency as a substitute for support.', effects: { aya_archive_openness: 0.10, proof_integrity: 0.10, p_mateus_truthfulness: -0.05 } }),
      option('challenge-omissions', 'Challenge omissions before discussing motive.', 'mateus_accountability',
        { text: 'Mateus names the offices omitted from his first account without exposing victims. The added detail makes the institutional chain harder to deny.', effects: { mateus_accountability: 0.10, truth_completeness: 0.10, proof_integrity: 0.05 } },
        { text: 'He cannot answer one question without exposing living witnesses. The tribunal records the limit rather than treating silence as proof of innocence.', effects: { witness_safety: 0.10, mateus_accountability: 0.05, public_reach: -0.05 } }),
      option('move-listeners', 'Move threatened listeners before testimony continues.', 'kiku_capacity',
        { text: 'Kiku coordinates a second room and the account resumes under safer conditions. The delay becomes part of the public timeline.', effects: { witness_safety: 0.10, care_capacity: 0.10, mateus_accountability: 0.05 } },
        { text: 'No safe continuation is possible. Mateus accepts that urgency does not entitle him to an audience, and the printers release only supported records.', effects: { ren_noncoercion: 0.10, mateus_accountability: 0.05, party_cohesion: 0.05 } }),
    ],
    accordOutcome: [
      'Admission Under Corroboration',
      'The tribunal afterword travels as a layered record: proven sequence, bounded testimony, visible uncertainty, and listener conditions. Mateus is neither erased nor restored to authority. Printers can reproduce the evidence without reproducing his control over it, and threatened listeners remain able to set distance from the process and its later copies.',
      'Choose what the first print run must show.',
      'public_reach',
      { text: 'The printers place the corroborated chain beside its gaps and safety limits. Readers can distinguish what is known, claimed, and intentionally withheld.', effects: { public_reach: 0.05, proof_integrity: 0.05, witness_safety: 0.05 } },
      { text: 'The first layout centers Mateus because his account is dramatic. Aya and the printers reorganize it around actions, offices, and independent sources.', effects: { aya_archive_openness: 0.05, network_consent: 0.05, mateus_accountability: 0.05 } },
    ],
    revisionOutcome: [
      'An Audience Is Not Owed',
      "The account stops when safe conditions fail. Mateus receives no promise that everyone must hear him, and the missing continuation remains plainly marked. Kiku moves people before paper; Aya publishes only the supported portion; the party carries a less complete record that does not purchase completeness with another person's exposure.",
      'State why the account ended.',
      'witness_safety',
      { text: 'The public note names the safety condition without identifying those at risk. Ending the session becomes an accountable decision rather than a mysterious omission.', effects: { witness_safety: 0.05, truth_completeness: 0.05, public_reach: 0.05 } },
      { text: 'The first note blames disorder in the room. Kiku replaces it with the actual capacity limit and leaves no implication that listeners failed the tribunal.', effects: { care_capacity: 0.05, aya_archive_openness: 0.05, ren_noncoercion: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw7-soldier-will-not-follow',
    chapterId: 'chapter-7',
    anchorBeatId: 'c7-03-aqueduct-names',
    placement: 'before-beat',
    sequenceRole: 'before-boss-decision',
    relatedEncounterIds: ['c7-name-slip-release'],
    entryRouteEffects: { ash_commitment: 0.05 },
    outcomeRouteEffects: { garrison_defection: 0.05 },
    title: 'The Soldier Who Will Not Follow',
    text: "A former retainer refuses both Kurozane's order and Genta's invitation to join another command. The party still needs route facts, and the soldier's group still needs food and an unarmed exit map. Genta must decide whether assistance can remain assistance when no service, allegiance, confession, or later gratitude is promised.",
    options: [
      option('supplies-no-service', 'Leave food and an unarmed exit map without recruitment.', 'genta_accountability',
        { text: 'Genta makes the handoff without rank language. The soldiers accept ordinary supplies and preserve their refusal to serve either command.', effects: { genta_accountability: 0.10, route_safety: 0.10, p_party_respects_limits: 0.05 } },
        { text: 'They reject a handoff from Genta himself. Ren leaves the supplies at a neutral marker, and no one calls the refusal ingratitude.', effects: { ren_noncoercion: 0.10, care_capacity: 0.10, genta_accountability: 0.05 } }),
      option('facts-not-assistance', 'Ask for route facts, not assistance.', 'p_party_respects_limits',
        { text: 'One soldier identifies a closed ferry and nothing more. Genta repeats the fact without turning the speaker into a scout.', effects: { truth_completeness: 0.10, route_safety: 0.10, genta_accountability: 0.05 } },
        { text: 'The question still sounds like command. Genta withdraws it, and the party chooses a slower route without treating silence as betrayal.', effects: { genta_accountability: 0.10, ren_noncoercion: 0.10, route_safety: -0.05 } }),
      option('acknowledge-leave', 'Acknowledge the refusal and leave without another request.', 'ren_noncoercion',
        { text: 'The soldier later sends an unsolicited warning through a civilian courier. Because no obligation was claimed, the warning remains a choice.', effects: { genta_accountability: 0.10, witness_safety: 0.10, route_safety: 0.05 } },
        { text: 'No warning follows. The party does not reinterpret the silence, and Genta plans for uncertainty instead of demanding proof of loyalty.', effects: { truth_completeness: 0.10, ren_noncoercion: 0.10, route_safety: -0.05 } }),
    ],
    accordOutcome: [
      'Help Without a Banner',
      'Supplies change hands without recruitment and route facts remain bounded to what was freely offered. Genta does not recover honor by collecting followers. His repair begins in the smaller discipline of accepting a refusal, removing rank from his verbs, and planning around people who owe him nothing in return afterward.',
      'Name the rule Genta must carry forward.',
      'genta_accountability',
      { text: 'Genta states that need creates no command authority. He writes the rule on the route map where his old rank marks used to appear.', effects: { genta_accountability: 0.05, ren_noncoercion: 0.05, party_cohesion: 0.05 } },
      { text: 'His first rule still praises voluntary service. Ren removes the praise, and Genta replaces it with a plain record of supplies and boundaries.', effects: { truth_completeness: 0.05, genta_accountability: 0.05, p_party_respects_limits: 0.05 } },
    ],
    revisionOutcome: [
      'Silence Is Not Betrayal',
      'The former soldiers offer no route fact, warning, or future alliance. The party leaves supplies where they can be taken without meeting. Genta plans around the information gap and refuses the familiar story in which people outside his command must eventually prove themselves useful to him or his cause later.',
      'Mark the uncertainty on the route.',
      'truth_completeness',
      { text: 'The map shows an unverified ferry and no accusation. A slower path remains available, preserving movement without inventing a hostile motive.', effects: { truth_completeness: 0.05, route_safety: 0.05, ren_noncoercion: 0.05 } },
      { text: 'One note still labels the soldiers unreliable. Genta crosses it out, accepts the added risk, and records only that no information was offered.', effects: { genta_accountability: 0.05, aya_archive_openness: 0.05, route_safety: -0.05 } },
    ],
  }),
  cluster({
    id: 'sw8-boats-with-conditions',
    chapterId: 'chapter-8',
    anchorBeatId: 'c8-04-lantern-breach',
    placement: 'before-beat',
    sequenceRole: 'before-boss-decision',
    relatedEncounterIds: ['c8-outer-court'],
    entryRouteEffects: { evacuation_capacity: 0.05 },
    outcomeRouteEffects: { salt_commitment: 0.05 },
    title: 'Boats With Conditions',
    text: "Neighborhood boat crews will help breach Kurohana's isolation, but they refuse to become an unnamed rebel fleet. Their capacity belongs first to evacuation, and every additional bundle changes inspection risk. Ren presents three bounded plans while making clear that local leads can reject, revise, or stop any contribution without penalty.",
    options: [
      option('evacuation-only', 'Use the boats for evacuation only.', 'p_party_respects_limits',
        { text: 'The crews accept the clear boundary and refuse evidence cargo. Their boats remain under local leads, with the party supplying guards only when asked.', effects: { witness_safety: 0.10, route_safety: 0.10, network_consent: 0.10 } },
        { text: 'Ren keeps asking operational questions after the limit is stated. The lead repeats it, and he records the correction without seeking another opening.', effects: { ren_noncoercion: 0.10, truth_completeness: 0.10, p_party_respects_limits: 0.05 } }),
      option('one-sealed-bundle', 'Add one independently sealed record bundle.', 'route_safety',
        { text: 'Crews accept one finite addition because its custody and destination are independent of passenger lists. Aya removes every identity from the seal.', effects: { public_reach: 0.10, route_safety: 0.10, proof_integrity: 0.05 } },
        { text: 'The bundle changes inspection risk too sharply. Aya removes it, and no one treats evacuation as a lesser use of the boats.', effects: { witness_safety: 0.10, aya_archive_openness: 0.10, ren_noncoercion: 0.05 } }),
      option('reserve-local-choice', 'Hold one reserve boat for its local lead to assign.', 'network_consent',
        { text: 'The reserve responds to actual need without waiting for party approval. Its lead can choose evacuation, care, or withdrawal as conditions change.', effects: { care_capacity: 0.10, network_consent: 0.10, route_safety: 0.05 } },
        { text: 'Ambiguous responsibility makes reserve status unsafe. The lead commits the boat to evacuation now and removes it from every later plan.', effects: { truth_completeness: 0.10, witness_safety: 0.10, route_safety: 0.05 } }),
    ],
    accordOutcome: [
      'A Fleet With Many Owners',
      'The boats carry visible conditions instead of a single rebel banner. Each lead owns departure, passenger limits, and withdrawal. The party coordinates signals without absorbing those decisions into its command. Kurohana sees a network acting together, but not a population conscripted into the heroes\' preferred image of resistance or victory.',
      'Confirm who can cancel a departure.',
      'network_consent',
      { text: 'Every local lead retains unilateral cancellation authority. Ren repeats the rule over the signal line before the first boat moves.', effects: { network_consent: 0.05, route_safety: 0.05, p_party_respects_limits: 0.05 } },
      { text: 'The first signal plan requires central confirmation. A boat lead rejects it, and the party rewrites the signal so local cancellation is immediate.', effects: { ren_noncoercion: 0.05, witness_safety: 0.05, truth_completeness: 0.05 } },
    ],
    revisionOutcome: [
      'Evacuation Is Enough',
      'The crews reject evidence cargo and reserve ambiguity. Their contribution remains evacuation under local command, with no apology and no secret test of courage. Aya reroutes the archive bundle by land. The breach plan becomes less elegant and more honest about what each neighborhood actually consented to carry that night.',
      'Remove the rejected use from every later order.',
      'ren_noncoercion',
      { text: 'Ren strikes the cargo language from the route cards and names evacuation as the boats\' complete mission. No later commander may silently restore it.', effects: { ren_noncoercion: 0.05, witness_safety: 0.05, network_consent: 0.05 } },
      { text: 'A reserve note survives on one copied map. Aya recalls it, publishes the correction, and assigns the archive bundle to an independent land route.', effects: { aya_archive_openness: 0.05, proof_integrity: 0.05, route_safety: -0.05 } },
    ],
  }),
  cluster({
    id: 'sw-enma-three-terms',
    chapterId: 'chapter-8',
    anchorBeatId: 'c8-05-gate-opened',
    placement: 'after-beat',
    sequenceRole: 'after-boss-consequence',
    relatedEncounterIds: ['c8-lady-enma'],
    spoolId: 'spool_enma',
    title: 'Three Terms for the Cinder Fan',
    text: "Lady Enma's third mask lies split on the Black Gate stones. The former court entertainer who became Kurozane's Cinder Fan remains conscious, dangerous, and responsible for the rain-dock pursuit, the archive-roof seizure, and years of audiences that turned selective mercy into terror. She offers route ciphers and court testimony but asks to leave under her own name. Nikola can set the Severed Dragon restraint; Mateus can identify a false blood command because he once wrote them; neither man is allowed to own the decision. Released soldiers, route delegates, and harmed witnesses require one exact term: death, rotating custody, or a revocable defection compact with no pardon.",
    options: [
      option('bounded-defection', 'Offer a witnessed defection compact: release every thrall, surrender every route cipher, testify, and accept revocable movement limits.', 'network_consent',
        { text: 'Enma names three hidden audiences and opens her cinder seals while separate route delegates retain the right to halt, narrow, or end the compact. Her assistance becomes monitored defection, not pardon or membership in the party.', outcomeKey: 'negotiated', effects: { enma_compact: 0.10, enma_testimony: 0.10, network_consent: 0.10 } },
        { text: 'Enma withholds the servant ledger and calls the omission privacy. Aya identifies two missing routes; the compact fails before it starts, and the released soldiers establish rotating custody under a Severed Dragon boundary.', outcomeKey: 'accord', effects: { enma_custody: 0.10, proof_integrity: 0.10, witness_safety: 0.10 } }),
      option('rotating-custody', 'Set the Severed Dragon restraint and transfer her to rotating civilian custody for testimony without a promise of release.', 'lise_oath_revision',
        { text: 'Nikola sets only the anti-vampire boundary, then gives its keys to three unrelated custodians. Enma survives to testify, while no hunter, priest, party member, or single village can turn custody into inherited authority.', outcomeKey: 'accord', effects: { enma_custody: 0.10, lise_oath_revision: 0.10, enma_testimony: 0.05 } },
        { text: 'Enma drives a hidden blood filament through the incomplete boundary toward the patient lane. Nikola severs it, Ren gives the witnessed fatal stop, and her death enters the record beside the failed restraint.', outcomeKey: 'revision', effects: { enma_killed: 0.10, witness_safety: 0.10, court_pressure: -0.05 } }),
      option('final-blood-duel', 'Accept her demand for a final blood duel only inside the witnessed ward, with the patient and evidence lanes protected.', 'court_pressure',
        { text: 'Enma uses the duel to reach the road behind Ren. Nikola and Mateus close the two exits without claiming the finishing stroke; the witnessed counterblow kills her before the Cinder Fan can reopen.', outcomeKey: 'revision', effects: { enma_killed: 0.10, court_pressure: -0.10, party_cohesion: 0.05 } },
        { text: 'The protected lanes deny Enma the theatrical death she expected. She drops the fan, gives Aya the first verifiable cipher, and accepts a compact whose witnesses may revoke every privilege she negotiates.', outcomeKey: 'negotiated', effects: { enma_compact: 0.10, enma_testimony: 0.10, truth_completeness: 0.05 } }),
    ],
    accordOutcome: [
      'Custody Without a Trophy',
      "The Severed Dragon restraint closes around Enma's blood commands without placing her inside Nikola's household power. Three custodians hold separate keys, harmed witnesses may set distance, and each interrogation requires an independent recorder. Mateus identifies ciphers but cannot question her alone. Enma is neither displayed as a conquered monster nor quietly absorbed into the resistance. She remains a living defendant and a dangerous source whose useful testimony does not erase the people she delivered to Kurozane's audiences.",
      'Write the first limit on her custody record.',
      'witness_safety',
      { text: 'The record forbids solitary custody, private questioning, blood access, and transport without a published destination. Enma signs beneath the restrictions while the three key holders sign beside, not above, one another.', effects: { enma_custody: 0.05, witness_safety: 0.05, proof_integrity: 0.05 } },
      { text: 'Nikola initially writes his house as guarantor. He strikes the title and replaces it with an expiring technical duty, leaving civilian custodians authority to end his access.', effects: { lise_oath_revision: 0.05, network_consent: 0.05, enma_testimony: 0.05 } },
    ],
    revisionOutcome: [
      'The Cinder Fan Ends',
      "Enma dies inside the witnessed ward after choosing a final attack or rupturing the restraint. Aya records who authorized the stop, what danger was immediate, and which questions now have no living answer. The party gains no trophy and no clean absolution. Her hidden ciphers must be reconstructed from seized fans, servants' accounts, and the routes she damaged. Kurozane loses his most capable audience keeper, but frightened officials scatter before they can be identified or offered bounded surrender.",
      'Separate the fatal record from the victory account.',
      'truth_completeness',
      { text: 'Aya preserves the immediate threat, the failed alternatives, and the testimony lost with Enma. The death is neither hidden nor made into proof that every captive enemy must die.', effects: { enma_killed: 0.05, truth_completeness: 0.05, aya_archive_openness: 0.05 } },
      { text: 'A route copy calls the killing purification. Nikola removes the inherited hunter language and replaces it with the exact witnessed necessity and its unresolved cost.', effects: { lise_oath_revision: 0.05, proof_integrity: 0.05, ren_noncoercion: 0.05 } },
    ],
    thirdOutcome: [
      'A Defection Under Witness',
      "Enma releases the attendants bound to her cinder seals, surrenders the rain-dock and archive-route ciphers, and gives Aya one claim that can be checked before the party enters Kurohana. The compact grants no pardon, office, or promise of safety after Kurozane falls. Each route may withdraw cooperation; every movement is reported; harmed witnesses need not meet her. Enma remains proud, implicated, and free only inside terms other people can revise. Her change is an action under pressure, not a declaration that the court years no longer count.",
      'State the first service that does not purchase forgiveness.',
      'enma_testimony',
      { text: 'Enma identifies a false inner-gate order, then waits while Aya confirms it from an independent record. The useful answer earns only the next bounded question, not trust or restored status.', effects: { enma_compact: 0.05, enma_testimony: 0.05, proof_integrity: 0.05 } },
      { text: 'Her first route claim omits two endangered attendants. Kiku suspends movement privileges until they are found, demonstrating that the compact can contract as well as reward cooperation.', effects: { witness_safety: 0.05, enma_testimony: -0.05, network_consent: 0.05 } },
    ],
  }),
  cluster({
    id: 'sw9-mateus-living-archive',
    chapterId: 'chapter-9',
    anchorBeatId: 'c9-04-yearless-bell',
    placement: 'before-beat',
    sequenceRole: 'before-boss-decision',
    relatedEncounterIds: ['c9-yearless-bell'],
    title: 'Mateus at the Living Archive',
    text: "Kurozane's living archive contains cipher layers Mateus can read and witness boundaries he has no right to cross. The party may use his knowledge without restoring priestly, foreign, or scholarly authority. Aya asks whether he should translate aloud, write only a key, or remain silent until a local custodian requests an answer.",
    options: [
      option('translate-aloud', 'Have Mateus translate aloud while Aya records.', 'mateus_accountability',
        { text: 'Mateus distinguishes his original work from later alterations and stops whenever Aya asks. The translation remains a witnessed act, not his private edition.', effects: { truth_completeness: 0.10, mateus_accountability: 0.10, proof_integrity: 0.05 } },
        { text: 'He starts controlling interpretation through pace and omission. Aya stops the session, records the attempt, and keeps only independently checked lines.', effects: { aya_archive_openness: 0.10, mateus_accountability: 0.05, p_mateus_truthfulness: -0.05 } }),
      option('cipher-key-only', 'Ask him to write only a bounded cipher key.', 'witness_safety',
        { text: 'The key permits independent reading later without bringing Mateus near witnesses. He labels where context is missing and claims no final interpretation.', effects: { proof_integrity: 0.10, witness_safety: 0.10, mateus_accountability: 0.05 } },
        { text: 'The key is incomplete without context. Mateus labels that limit instead of expanding his access, and Aya preserves the unfinished tool.', effects: { truth_completeness: 0.10, aya_archive_openness: 0.10, public_reach: -0.05 } }),
      option('wait-for-custodian', 'Keep him silent unless a local custodian asks.', 'network_consent',
        { text: 'Mateus accepts silence and follows guard instructions. A custodian later asks one narrow question, which he answers carefully in writing.', effects: { mateus_accountability: 0.10, network_consent: 0.10, party_cohesion: 0.05 } },
        { text: 'He volunteers a warning before being asked. The guard stops him; he submits it in writing and accepts that urgency does not erase the rule.', effects: { truth_completeness: 0.10, mateus_accountability: 0.05, p_mateus_truthfulness: -0.05 } }),
    ],
    accordOutcome: [
      'Knowledge Under Revocable Terms',
      'Mateus contributes a bounded key whose use can be stopped, checked, and reassigned. Aya and local custodians retain interpretation authority. His change of heart appears as costly restraint and useful testimony, not absolution, restored office, or a claim that European knowledge must lead the resistance or define its future direction.',
      'State what Mateus does not receive in return.',
      'mateus_accountability',
      { text: 'The record grants no command, pardon, private access, or restored title. Mateus signs the limits before the key enters local custody.', effects: { mateus_accountability: 0.05, network_consent: 0.05, truth_completeness: 0.05 } },
      { text: 'One draft thanks Mateus in language that implies restoration. Nikola removes it without substituting the language of noble honor, and the final receipt records only the bounded work completed.', effects: { lise_oath_revision: 0.05, aya_archive_openness: 0.05, party_cohesion: 0.05 } },
    ],
    revisionOutcome: [
      'The Translation Stops',
      "Aya ends the session when Mateus begins to control interpretation. The archive keeps the checked lines, the attempted omission, and the unfinished cipher key. He remains available under guard, but usefulness does not entitle him to continue. The party enters Kurozane's final chamber with a narrower and more trustworthy record.",
      'Preserve the stopped boundary in the archive.',
      'aya_archive_openness',
      { text: 'Aya timestamps the halt and separates verified lines from abandoned interpretation. Later readers can see why the account ends where it does.', effects: { aya_archive_openness: 0.05, proof_integrity: 0.05, witness_safety: 0.05 } },
      { text: 'The first copy omits the attempted control. Nikola restores the note, refusing to make Mateus easier to forgive or either man easier to honor by making the record smoother.', effects: { lise_oath_revision: 0.05, truth_completeness: 0.05, p_mateus_truthfulness: -0.05 } },
    ],
  }),
  cluster({
    // Save-compatible cluster id: the old epilogue corrections scene now owns
    // the final post-boss political consequence.
    id: 'sw10-corrections-desk',
    chapterId: 'chapter-9',
    anchorBeatId: 'c9-05-dawn-at-observatory',
    placement: 'after-beat',
    sequenceRole: 'after-boss-consequence',
    relatedEncounterIds: ['c9-kurozane'],
    title: 'The Last Command',
    text: "Kurozane lies alive in the broken command circle with Nikola's lance beneath his jaw. Around them, the observatory's last ring of crucified and impaled Kirishitan victims catches the same dawn as the throne. Two rescued prisoners are already moving toward Kiku's evacuation line; the dead remain named evidence, not decoration for a victor's portrait. The Yearless Bell is silent, but garrisons, granaries, Oni collars, and registry offices still wait for instructions tied to the shogun's blood. Three outer bells are already demanding a succession command. Killing Kurozane may rupture those bindings and hand every rival governor an emergency. The Severed Dragon pattern can hold him mortal and commandless long enough to return the seals, but no ward can manufacture repentance. 'Keep me and inherit my necessity,' Kurozane says. 'Kill me and inherit my war.' Ren answers that those are the choices his regime built, not the only terms the living must accept.",
    options: [
      option('witnessed-return', 'Order the seals returned one by one before independent route witnesses.', 'network_consent',
        { text: "Salt, Ash, and Paper delegates enter by separate stairs and name the powers Kurozane must surrender. Nikola holds only the severing line. Mateus reads each blood command as it dies and accepts no title in exchange. When Kurozane calls this government by committee, Nikola answers, 'No. Government without you. I understand the distinction is painful.'", effects: { network_consent: 0.10, lise_oath_revision: 0.10, mateus_accountability: 0.05 } },
        { text: "Kurozane returns the ceremonial seals and conceals the granary command inside his left hand. Aya catches the missing office. He reaches through it to starve the routes; Ren calls the fatal stop before the binding tears. The lance falls as rival riders are already racing to claim the orphaned stores.", effects: { proof_integrity: 0.10, court_pressure: 0.10, truth_completeness: 0.05 } }),
      option('provisional-binding', 'Hold Kurozane until the route councils can define a transfer no victor owns.', 'proof_integrity',
        { text: "The binding receives a public expiration at the next dawn and no private hunter custody. Local delegates inventory every office before accepting it. Kurozane asks which of them is shogun now. 'That impatience is the disease,' Mateus says. No one accepts the throne in order to answer him faster.", effects: { proof_integrity: 0.10, ren_noncoercion: 0.10, network_consent: 0.05 } },
        { text: "The first draft makes Nikola sole keeper of the bond. He tears out his own authority clause. During the delay Kurozane ruptures the provisional line and reaches for an outer bell. Route witnesses authorize the fatal stop rather than cure one immortal office by placing it in a foreign nobleman's hands.", effects: { lise_oath_revision: 0.10, court_pressure: 0.05, party_cohesion: 0.05 } }),
      option('execution-demand', 'Demand execution now, before the blood court can regroup.', 'court_pressure',
        { text: "Nikola lowers the Longinus point until Kurozane feels his immortality fail around it. The shogun looks past the blade and sees route messengers already carrying orders that did not come from him. He chooses witnessed surrender, not remorse. Mateus warns Nikola not to call fear conversion. 'I was going to call it excellent reach,' Nikola says.", effects: { court_pressure: -0.10, truth_completeness: 0.10, network_consent: 0.05 } },
        { text: "The demand becomes the act before every command can be inventoried. Kurozane dies. The central Bell stops; distant bells answer competing hands. Before the blood has cooled, messengers report governors claiming emergency authority over roads, rice, and the surviving Oni.", effects: { court_pressure: 0.10, route_safety: -0.10, witness_safety: -0.05 } }),
    ],
    accordOutcome: [
      'The Seals Returned',
      "Independent confirmations arrive from roads Kurozane believed would collapse without him. Salt runners have opened the rice stores. Ash defectors hold the outer garrison without a purge. Paper witnesses are copying the registry faster than his clerks can hide it. Kurozane asks what will hold the country together when no immortal body commands the center. Ren answers, 'People who can refuse one another and still share a road.' Mateus tells his former master that a mortal peace is allowed to be unfinished. Nikola tells him surrender is not a sacrament and therefore requires no miracle. Kurozane looks toward the capital, hears orders moving without his blood, and at last concedes the fact his reign could never permit: the country has survived his absence for one full hour. He returns the military seal, the registry seal, the granary seal, and finally the black bell seal. The Severed Dragon boundary strips each office from his body. He is taken alive under rotating guard, defeated and without title. The living prisoners leave first. Witnesses catalogue the execution rows before any beam is dismantled. No one calls the transfer forgiveness or voluntary reform. It is Kurozane's first public act in which his survival no longer requires everyone else's obedience—and the first dawn he must endure as only a man.",
      'Record what the former shogun does not retain.',
      'network_consent',
      { text: "The receipt names every surrendered office, every temporary custodian, and every route empowered to refuse the arrangement. Kurozane signs beneath the limits, then reaches by habit for a title that is no longer written there.", effects: { network_consent: 0.05, truth_completeness: 0.05, ren_noncoercion: 0.05 } },
      { text: "A court copy calls the act voluntary reform. Aya crosses the phrase out. Nikola supplies 'unconditional capitulation'; Mateus supplies 'witnessed surrender under defeat.' Aya keeps the accurate version and files Nikola's in the margin.", effects: { aya_archive_openness: 0.05, proof_integrity: 0.05, mateus_accountability: 0.05 } },
    ],
    revisionOutcome: [
      'The Empty Throne Mobilizes',
      "The Longinus point enters beneath Kurozane's jaw after immediate execution or a failed transfer forces the fatal stop. For one breath, every black bell in the observatory answers. Then the central Bell goes silent. The silence does not travel. East of Kurohana, a governor seizes three rice stores in the name of continuity. North, a court cousin claims the patrol seals. Along the old road, surviving Oni kneel to whichever officer can reproduce the loudest fragment of Kurozane's command. Red dawn riders pass the first evacuation column before the party reaches the outer archive. No explosion erases the evidence, and no voice declares execution uniquely wicked. The consequence is the civil war Kurozane built into a regime with one immortal transfer mechanism. The party can keep roads open, evacuate witnesses, and carry proof into the fighting. It cannot make the vacuum safe after the blade has fallen.",
      'Carry the execution record into the emergency route plan.',
      'court_pressure',
      { text: "Aya records the time of death, the unsupported commands that failed with it, and the first rival claims. Ren marks evacuation roads without labeling every mobilized district an enemy. The record leaves no blank space where a clean victory might later be invented.", effects: { truth_completeness: 0.05, route_safety: 0.05, aya_archive_openness: 0.05 } },
      { text: "Nikola begins the Dražanić phrase 'necessary cleansing,' stops, and drives his pen through it. He writes that the Covenant failed when it offered only a blade after surrender became difficult. Mateus, holding Kiku's blood-soaked bandage, signs as witness rather than editor.", effects: { lise_oath_revision: 0.05, ren_noncoercion: 0.05, party_cohesion: 0.05 } },
    ],
  }),
]);
